### ISSUE TITLE
Google spreadsheet mapping file validator

### ISSUE THREAD

**Issue by maasha** [biocore/qiime#1014]
The option of using remote mapping files in QIIME is quite wonderful. I was wondering if it was possible to write a mapping file validator using the script-editor in Google spreadsheet? It would be absolutely fantastic if errors and warnings were raised in the spreadsheet instead of a subsequent step using the check_id_map.py script - that would save a lot of trouble.

**Comment by jairideout** [comment]
We [just announced](https://groups.google.com/d/topic/qiime-forum/Ph63st7UEjQ/discussion) an initial public alpha release of Keemei, a tool for validating QIIME mapping files in Google Sheets. For more info about Keemei visit http://keemei.qiime.org.
