### ISSUE TITLE
pick_open_reference_otus.py should give more informative error messages

### ISSUE THREAD

**Issue by walterst** [biocore/qiime#1075]
If a situation happens, such as all sequences being filtered out in the prefilter step (e.g. sequences are not in the same orientation as the reference data), all sequences are filtered out, and an uninformative crash such as the one below occurs. There should be sanity checks for empty fasta files to help determine the cause of the crash.

Command run was:
 pick_otus.py -i otus-usearch61/prefilter_otus//prefiltered_seqs.fna -o otus-usearch61/step1_otus -r /opt/qiime/gg-13.5/gg_13_5_otus/rep_set/97_otus.fasta -m usearch61_ref  --suppress_new_clusters
Command returned exit status: 1
Stdout:

Stderr
Traceback (most recent call last):
  File "/opt/qiime/qiime-1.7.0-release/bin/pick_otus.py", line 771, in <module>
    main()
  File "/opt/qiime/qiime-1.7.0-release/bin/pick_otus.py", line 705, in main
    otu_prefix=otu_prefix, HALT_EXEC=False)
  File "/opt/qiime/qiime-1.7.0-release/lib/qiime/pick_otus.py", line 1393, in **call**
    HALT_EXEC=HALT_EXEC
  File "/opt/qiime/qiime-1.7.0-release/lib/qiime/pycogent_backports/usearch.py", line 1825, in usearch61_ref_cluster
    raise ApplicationError, ('Error running usearch61. Possible causes are '
cogent.app.util.ApplicationError: Error running usearch61. Possible causes are unsupported version (current supported version is usearch v6.1.544) is installed or improperly formatted input file was provided

**Comment by tuony** [comment]
hi ialso face this problem how can i solve it

**Comment by ElDeveloper** [comment]
@tuony the fix for this problem was merged and released as part of the 1.9.x series, if you are seeing this traceback, I'm guessing you are using an older version of QIIME?

For specific steps on how to troubleshoot this problem, I would suggest going to http://forum.qiime.org
