### ISSUE TITLE
Add absolute minimum read length option to split_libraries_fastq.py

### ISSUE THREAD

**Issue by and3k** [biocore/qiime#1103]
Currently, `split_libraries_fastq.py` only supports the filtering criteria for relative minimum read length (`--min_per_read_length_fraction`), which is always calculated from the first read.

For FASTQ files with varying read lengths, an absolute minimum read length option would be useful (e.g. `--min_per_read_length` or `--min_per_read_length_absolute` or `--min_per_read_length_nt`?)

For backward compatibility it could be just set to None by default, and if set would take precedence over `--min_per_read_length_fraction`?

Relevant discussion: https://groups.google.com/forum/#!topic/qiime-forum/bLFfsn-01rI

**Comment by AmandaBirmingham** [comment]
+1 
Would be very useful for those who have to work with Ion Torrent data, which tends to have numerous sequences with premature truncation and thus a wide variety of read lengths.
