### ISSUE TITLE
beta_diversity_through_plots.py should include --ignore_missing_samples flag

### ISSUE THREAD

**Issue by lkursell** [biocore/qiime#1353]
If you run the beta_diversity_through_plots.py command on an OTU table that is a subset of what's in the mapping file, you'll get an error every time at the make_emperor.py step, which requires that you pass the --ignore_missing_samples.py flag. This could be dealt with in the parameters file, but given this is supposed to be a overarching workflow script, having this common flag as a default parameter in the beta_diversity_through_plots.py script would be very helpful.

**Comment by stamper-c** [comment]
I am running into the same problem. I have a mapping file that contains a subset of the samples in the OTU table. Is there a way to pass the flag --ignore_missing_samples without putting it into a parameters file? The error message suggests using this flag. However, if you use the --ignore_missing_samples flag the beta_diversity_through_plots.py throws an error that there is no such option. Thanks.

**Comment by gregcaporaso** [comment]
@stamper-c, can you please post your question to the [QIIME Forum](http://forum.qiime.org)? We try to address these types of technical support questions there, as it's then easier for others to find answers when they have the same questions. Thank you!
