### ISSUE TITLE
stricter handling of parameters files?

### ISSUE THREAD

**Issue by jairideout** [biocore/qiime#1476]
Should we update the parameters file parser/handler to error if the file isn't formatted correctly, or if a script name / parameter isn't recognized (e.g., due to misspelling)?

This issue comes up very frequently on the forum, where a user will have an incorrectly formatted parameters file, or they've misspelled or mixed up a script / parameter name. The current behavior ignores virtually all issues with the file and uses script defaults, so users don't know that they've made a mistake when they created the file, and are often confused why they weren't able to override default behavior.

**Comment by staemmlord** [comment]
+1

**Comment by wasade** [comment]
Can we go full .yaml?

**Comment by josenavas** [comment]
What about using python's ConfigParser?

**Comment by gregcaporaso** [comment]
We won't be making any changes to this in QIIME 1 as we're in maintenance mode only on this project. See [this RFC](https://github.com/qiime2/rfcs/pull/5) for discussion of this topic for QIIME 2.
