### ISSUE TITLE
Illumina ipython notebook tutorial not linked properly

### ISSUE THREAD

**Issue by lkursell** [biocore/qiime#1567]
http://nbviewer.ipython.org/github/qiime/qiime/blob/1.8.0/examples/ipynb/illumina_overview_tutorial.ipynb -> This link from http://qiime.org/tutorials/illumina_overview_tutorial.html gives a 404 error

**Comment by klm0318** [comment]
Hello! I know this was closed a long time ago, but I am also having trouble with a broken link in the tutorial. Can you please help? Thanks.

**Comment by gregcaporaso** [comment]
@klm0318, are you still having this issue? I'm able to get to the page ok, so it may have been a temporary outage.
