### ISSUE TITLE
qiime.util - cannot import name get_tmp_filename

### ISSUE THREAD

**Issue by prehensilecode** [biocore/qiime#1632]
I have Python 2.7.8. My installed modules (from pip list):

backports.ssl-match-hostname (3.4.0.2)
biom-format (2.0.1)
brokit (0.0.0-dev)
certifi (14.05.14)
cogent (1.5.3)
docutils (0.12)
future (0.12.4)
gdata (2.0.18)
h5py (2.3.1)
ipython (2.1.0)
Jinja2 (2.7.3)
MarkupSafe (0.23)
matplotlib (1.3.1)
natsort (3.4.0)
nose (1.3.3)
numpy (1.7.1)
pandas (0.14.1)
pip (1.5.6)
Pygments (1.6)
pynast (1.2.2)
pyparsing (2.0.2)
pyqi (0.3.2)
python-dateutil (2.2)
pytz (2014.4)
qcli (0.1.0)
qiime (1.8.0-dev)
scikit-bio (0.1.4)
scikit-learn (0.15.0)
scipy (0.14.0)
setuptools (5.4.1)
six (1.7.3)
Sphinx (1.2.2)
timeseries (0.5.0)
tornado (4.0)
wsgiref (0.1.2)

And print_qiime_config.py:
# System information

```
     Platform:  linux2
```

   Python version:  2.7.8 (default, Jul 18 2014, 17:38:12)  [GCC 4.8.1]
Python executable:  /mnt/HA/opt/qiime/gcc/64/bin/python
# Dependency versions

```
                 PyCogent version:  1.5.3
                    NumPy version:  1.7.1
               matplotlib version:  1.3.1
              biom-format version:  2.0.1
                     qcli version:  0.1.0
            QIIME library version:  1.8.0-dev
             QIIME script version:  1.8.0
    PyNAST version (if installed):  1.2.2
                  Emperor version:  Not installed.
```

RDP Classifier version (if installed):  Not installed.
          Java version (if installed):  Not installed.
# QIIME config values

```
                 blastmat_dir:  None
```

   template_alignment_lanemask_fp:  None
                    jobs_to_start:  1
pynast_template_alignment_blastdb:  None
                         sc_queue:  all.q
            denoiser_min_per_core:  50
      topiaryexplorer_project_dir:  None
     pynast_template_alignment_fp:  None
assign_taxonomy_id_to_taxonomy_fp:  None
                         temp_dir:  /tmp/
assign_taxonomy_reference_seqs_fp:  None
                     torque_queue:  friendlyq
                      blastall_fp:  blastall
                 seconds_to_sleep:  2
                  cluster_jobs_fp:  None

Now, using ipython:
In [1]: import qiime.util
## In [2]: from qiime.util import get_tmp_filename

ImportError                               Traceback (most recent call last)
<ipython-input-2-042684832fec> in <module>()
----> 1 from qiime.util import get_tmp_filename

ImportError: cannot import name get_tmp_filename

**Comment by trustodia** [comment]
@prehensilecode how do we solve this problem? I need to run pick_otus.py

**Comment by gregcaporaso** [comment]
@prehensilecode, do you have the option to upgrade to QIIME 1.9.1? It is pretty straight-forward with our [new conda install instructions](http://qiime.org/install/install.html). I'm not sure why you're running into this issue, but we're no longer officially supporting QIIME 1.8.0 (it's a couple of years old) in favor of supporting QIIME 1.9.1. QIIME 1.9.1 has a lot of improvements over QIIME 1.8.0. My expectation is that if you upgrade to QIIME 1.9.1, you won't have this issue anymore.

**Comment by trustodia** [comment]
How do I upgrade?, because I am currently using qimme 1.9.1. I have the latest qiime and qiime scripts.

**Comment by jairideout** [comment]
Can you please post your question on the [QIIME 1 forum](http://forum.qiime.org)? That's where we provide user support.
