### ISSUE TITLE
get rid of OpenBLAS warning on the AWS instance

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/qiime#1704]
This prints with nearly every QIIME command call on the AWS instance:

```
OpenBLAS : Your OS does not support AVX instructions. OpenBLAS is using Nehalem kernels as a fallback, which may give poorer performance.
```

Anyone know how to get rid of this? This is annoying (e.g., in workshops) because it looks like a QIIME problem. For example:

![screenshot 2014-11-01 21 03 13](https://cloud.githubusercontent.com/assets/192372/4874207/3137f80c-6245-11e4-83aa-b47f15fb6956.png)

**Comment by gregcaporaso** [comment]
This is addressed as part of the [new AMI build instructions](https://github.com/biocore/qiime/wiki/Building-the-QIIME-AMI).

**Comment by ElDeveloper** [comment]
YEAH WIKI!!!! We should move anything that can be shared and that
currently exists as a google-doc into the wiki.

**Comment by gregcaporaso** [comment]
We were thinking that, to get away from all of the random google docs that are easy to lose track of. We should do this as we use/update docs though, rather than make a concerted effort to port documents that in some cases we might not need anymore.

**Comment by ElDeveloper** [comment]
Yes, I agree.

Yoshiki Vázquez-Baeza
