### ISSUE TITLE
update notebook tutorials and rest of the documentation

### ISSUE THREAD

**Issue by jairideout** [biocore/qiime#1781]
@gregcaporaso and I will work on this after #1777 is merged.

**Comment by jairideout** [comment]
Be sure to update the EC2 tutorial, some of the instructions are out of date.

**Comment by gregcaporaso** [comment]
The EC2 tutorial should include instructions for starting the IPython Notebook server.

**Comment by gregcaporaso** [comment]
The install document should mention the programs that are attempted to be installed by setup.py (these are: uclust, FastTree, SortMeRNA, SUMACLUST, and swarm).

**Comment by ElDeveloper** [comment]
> (There's probably a better way than using screen, but I don't see it here.)

Maybe `nohup`, only downside is that to stop the process you would have to kill it through the PID (I don't know another way to do it).

**Comment by gregcaporaso** [comment]
A couple of very minor changes for the ITS tutorial (if we don't get to them, it's not a big deal):

- [ ] *You can review all of the files that are created by passing the path to the output directory to the FileLink function.* -> *You can review all of the files that are created by passing the path to the ``index.html`` file in the output directory to the FileLink function.*

- [ ] *First, obtaining the tutorial data and reference database:* -> *First, we obtain the tutorial data and reference database:*

**Comment by jairideout** [comment]
The following tutorials still need updating:

- [ ] Preparing raw Illumina data in different formats for use with QIIME
- [ ] Extracting Barcodes from fastq data for compatibility with split_libraries_fastq.py
- [ ] Performing Procrustes Analysis
- [ ] Analysis of shotgun sequencing data
- [ ] Basic Unix/Linux/OS X commands
- [ ] Working with QIIME on Amazon Web Services EC2

@gregcaporaso and I will take a pass through tomorrow.
