### ISSUE TITLE
update qiime-deploy instructions

### ISSUE THREAD

**Issue by jairideout** [biocore/qiime#1802]
Now that qiime-deploy doesn't install Python, R, or their respective requisite packages, the qiime-deploy readme needs to be updated to explain how to obtain a full QIIME install.

Assigning to myself, adding the issue here instead of on the qiime-deploy issue tracker so we don't forget to update during the 1.9.0 release.

**Comment by gregcaporaso** [comment]
qiime-deploy should no longer add defaults for:
 ``assign_taxonomy_id_to_taxonomy_fp``
 ``assign_taxonomy_reference_seqs_fp``
 ``pynast_template_alignment_fp``
 ``pick_otus_reference_seqs_fp``

**Comment by jairideout** [comment]
Fixed in https://github.com/qiime/qiime-deploy/pull/76 and https://github.com/qiime/qiime-deploy-conf/pull/138.
