### ISSUE TITLE
Installation documentation addition

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiime#1817]
[Andrew](https://groups.google.com/d/msg/qiime-forum/-y1J7uQeS3w/tJYqP-krnYQJ) suggested the following addition to the installation instructions:

> For the person with a bare ubuntu install, the qiime install instructions apparently must be prefaced with the following two commands:
> sudo apt-get install python-pip
> sudo apt-get install python-dev

**Comment by colinbrislawn** [comment]
I second the request for an installation tutorial which does not require sudo privileges. My lab runs RHEL servers and I would be happy to test a 'normal' user install.

(Perhaps this should be listed as a different Issue).

**Comment by antgonza** [comment]
Have you tried https://github.com/qiime/qiime-deploy#qiime-deploy ?
The sudo sections are regular packages that most, if not all, main
computers (should) have.

**Comment by jairideout** [comment]
qiime-deploy no longer installs the Python dependencies now that we're relying on standard Python package installers (e.g., `pip`). :+1: for updating the install instructions to describe a non-sudo install.

**Comment by antgonza** [comment]
Forgot about that! Thanks.
