### ISSUE TITLE
update tutorial s3 links

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/qiime#1823]
There are several links in the QIIME tutorials to an s3 bucket that won't exist any more when the release goes live. These should all be updated to point to a new location. Currently I have them in Dropbox, but we should move to a more permanent location before the release. The URLs that need to be replaced are:

```
https://s3.amazonaws.com/s3-qiime_tutorial_files/keyboard.zip
https://s3.amazonaws.com/s3-qiime_tutorial_files/costello_whole_body/costello_timeseries_map.txt
https://s3.amazonaws.com/s3-qiime_tutorial_files/costello_whole_body/forearm_only_unweighted_unifrac_dm.txt
https://s3.amazonaws.com/s3-qiime_tutorial_files/88_soils.zip
https://s3.amazonaws.com/s3-qiime_tutorial_files/filtering_otus_tutorial_data.zip
https://s3.amazonaws.com/s3-qiime_tutorial_files/moving_pictures_procrustes_demo.tgz
https://s3.amazonaws.com/s3-qiime_tutorial_files/shotgun_analysis_gn.tgz
https://s3.amazonaws.com/s3-qiime_tutorial_files/sourcetracker_tutorial_files.tgz
https://s3.amazonaws.com/s3-qiime_tutorial_files/taxa_summary_comparison_tutorial_data.zip
```

In all cases, substituting ``https://s3.amazonaws.com/s3-qiime_tutorial_files/`` with ``https://dl.dropboxusercontent.com/u/2868868/s3-qiime_tutorial_files/``will work. 

@wasade, would it be possible to have these files placed under ``ftp.microbio.me``?

**Comment by antgonza** [comment]
The files have been added here: ftp://ftp.microbio.me/qiime/, thanks
for the help @ElDeveloper.

**Comment by gregcaporaso** [comment]
Thanks! @jairideout and I will update the links when we pass through the
docs this week.
