### ISSUE TITLE
--minimum_failure_threshold not properly implemented

### ISSUE THREAD

**Issue by mlangill** [biocore/qiime#1830]
Within the script pick_open_reference_otus.py the --minimum_failure_threshold is properly described in the documentation to decide whether or not to do steps 2 and 3 (or skip right to steps 4) by comparing this threshold (default being set to 100,000 which by the way is not included in the documentation) to the **number of sequences failing the reference picking step**. However, the threshold is improperly compared to the **number of subsampled sequences**. 

This bug causes the pipeline to skip steps 2 and 3 when the defaults are used even with very large datasets (e.g. 5 million failed reads are attempted to be de novo otu picked in step 4). 

A PR will be issued shortly to address this.

**Comment by gregcaporaso** [comment]
Thanks @mlangill! Do you have an ETA on your pull request? We're going to tag another release candidate shortly, and ideally we'd get this change in there. 

Also, was this discovered with QIIME 1.9.0-rc1? 


cc @ekopylova

**Comment by mlangill** [comment]
Yes, this was on QIIME 1.9.0-rc1. PR should be sent in about 5 minutes.

**Comment by ekopylova** [comment]
This bug is in QIIME 1.9.0-rc1, indeed the computation uses the subsampled sequences file rather than the original failures file (see https://github.com/biocore/qiime/blob/master/qiime/workflow/pick_open_reference_otus.py#LN746-748), that's an overlook on my part. Thanks for spotting this!

**Comment by mlangill** [comment]
BTW, where is the help documentation created for each script? The default for --minimum_failure_threshold is not listed with '-h', but I can't find where to add it?

**Comment by gregcaporaso** [comment]
The help documentation is in ``Qiime/scripts/pick_open_reference_otus.py`` (the html docs are auto-generated from that).

**Comment by ekopylova** [comment]
Adding '[default: %default]' at the end of help in make_option('--minimum_failure_threshold') will show the default with '-h'.
