### ISSUE TITLE
are there basic linux utilities we should install in the 1.9.0 AMI?

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/qiime#1838]
I'm thinking things that are easy to install, which we may have not had in there in the past. For example, we definitely want ``htop``.

**Comment by jairideout** [comment]
~~We definitely need `sl`.~~

**Comment by ElDeveloper** [comment]
Not sure if these are already available, but we definitely want screen
and vim.

**Comment by jairideout** [comment]
:+1:, these are already available in the AMI.

**Comment by gregcaporaso** [comment]
Closing as everything that was suggested will be in the 1.9.0 AMI. Thanks!
