### ISSUE TITLE
misleading BIOM error message if no h5py/HDF5

### ISSUE THREAD

**Issue by jairideout** [biocore/qiime#1855]
If h5py/HDF5 isn't installed, attempting to read a BIOM HDF5 file with `biom.load_table` results in a misleading error message:

```
Traceback (most recent call last):
  File "/usr/local/bin/observation_metadata_correlation.py", line 238, in <module>
    main()
  File "/usr/local/bin/observation_metadata_correlation.py", line 175, in main
    bt = load_table(opts.otu_table_fp)
  File "/usr/local/lib/python2.7/dist-packages/biom/parse.py", line 553, in load_table
    raise TypeError("%s does not appear to be a BIOM file!" % f)
TypeError: otu_table.biom does not appear to be a BIOM file!
```

I created a corresponding issue on the BIOM issue tracker (https://github.com/biocore/biom-format/issues/584).

This error is likely to be frequently encountered by QIIME users since h5py/HDF5 is optional and not part of the base install. If a user obtains a BIOM HDF5 file (e.g., from a collaborator) and tries to use it within QIIME, they will receive this error message.

How should we handle this? We could wrap `load_table` in `qiime.util` to catch this error message and provide a better one, or do a minor BIOM release (not excited about either of these options though).

cc @gregcaporaso @wasade @ElDeveloper @adamrp @josenavas

**Comment by ElDeveloper** [comment]
I vote for doing a minor biom release, though this is a tricky one. The
function in biom should check the file's magic number and if it
corresponds to the one of an HDF5 file, then it should also have H5PY
installed, else raise the error message.

:-1: for wrapping this in QIIME, that tends to get dirty and fragile
very quickly.

**Comment by gregcaporaso** [comment]
:+1: for the minor biom release. Thanks @ElDeveloper!

**Comment by jairideout** [comment]
This was fixed in https://github.com/biocore/biom-format/pull/586
