### ISSUE TITLE
change parse_biom_table calls to load_table

### ISSUE THREAD

**Issue by jairideout** [biocore/qiime#1859]
@ElDeveloper and I chatted about this offline. There's a mixture of `biom.parse.parse_biom_table` and `biom.load_table` calls throughout the codebase. I think these should be updated to use `biom.load_table` for consistent handling and error messages when loading BIOM tables. 

Related to #1855.

cc @gregcaporaso @wasade @josenavas @adamrp

**Comment by gregcaporaso** [comment]
:+1:
