### ISSUE TITLE
Add a note describing the benefits of using HDF5

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiime#1867]
Since HDF5 is optional and users may wonder whether or not they'll want to use this dependency, we should provide a small description about the benefits and reasons why you might want to use HDF5 instead of JSON. Not sure where this should be in the documentation.

**Comment by jairideout** [comment]
:+1:, we have a brief note describing this in the [install docs](https://github.com/biocore/qiime/blob/master/doc/install/install.rst), but we should probably expand and/or move this description somewhere more obvious.

**Comment by ElDeveloper** [comment]
I think that's a good place for a small note, but adding a more
comprehensive description would be nice. Perhaps in the OTU table
section of the file formats page:
http://qiime.org/documentation/file_formats.html

**Comment by jairideout** [comment]
:+1: , then we can link to it from the install page

**Comment by gregcaporaso** [comment]
@ElDeveloper, could you write the text and post it as a comment here? Then @jairideout and I could include in the file formats page?

**Comment by ElDeveloper** [comment]
@gregcaporaso, I'll do this over the weekend.

**Comment by ElDeveloper** [comment]
What about something like this:

As of version 1.8.0-dev, QIIME supports version
[1.0](http://biom-format.org/documentation/format_versions/biom-1.0.html)
and
[2.1](http://biom-format.org/documentation/format_versions/biom-2.1.html)
of the BIOM format. The main distinction between these two versions is
the underlying file format JSON (for version 1.0) and HDF5 (for version
2.1), the later is recommended for large datasets as it provides an
efficient way to store and access thousands of samples by observations.
If the [HDF5](http://www.hdfgroup.org/HDF5/) libraries and
[h5py](http://www.h5py.org) are installed, QIIME will use HDF5 to write
every table it produces. Note however that if needed, you can convert
between file-formats using `biom convert`.

**Comment by jairideout** [comment]
Thanks! I integrated this into the file format docs (and expanded a little bit). The changes are in #1898 (see [this commit](https://github.com/biocore/qiime/commit/4f2d8bad7838a60a79b7073d7bed817fee6486fa)).

**Comment by ElDeveloper** [comment]
Awesome, that looks great. Thanks!!

Yoshiki Vázquez-Baeza
