### ISSUE TITLE
clean up moving pictures 1.9.0 tutorial tarball

### ISSUE THREAD

**Issue by jairideout** [biocore/qiime#1872]
The [Moving Pictures 1.9.0 tutorial tarball](ftp://ftp.microbio.me/qiime/tutorial_files/moving_pictures_tutorial-1.9.0.tgz) has several garbage files that clutter the directories when viewed with `FileLinks`, including `.DS_Store` and `._` files. @gregcaporaso and I are working on updating this tarball as we work on #1781.

@ElDeveloper are you available to upload a new tarball when it's ready?

**Comment by ElDeveloper** [comment]
Sure thing.

**Comment by gregcaporaso** [comment]
Also, there is a ``moving_pictures_tutorial-1.9.0.tgz.1`` file up there that can be deleted.

**Comment by gregcaporaso** [comment]
This is fixed, thanks @ElDeveloper!

**Comment by ElDeveloper** [comment]
No problem!
