### ISSUE TITLE
Merge_mapping_files.py documentation

### ISSUE THREAD

**Issue by lkursell** [biocore/qiime#1874]
The script fails if the mapping file doesn't contain the requisite SampleID, BarcodeSequence, and LinkerPrimerSequence as the first three columns, which is ok, but the error message is just a KeyError currently.

**Comment by jairideout** [comment]
Can you please post the full `KeyError` message that you receive?

**Comment by jairideout** [comment]
Nevermind, I was able to reproduce this:

```
KeyError: 'BarcodeSequence'
```

We should get this fixed for 1.9.0. Any takers?
