### ISSUE TITLE
split_libraries_fastq.py is ~7x slower than 1.8.0

### ISSUE THREAD

**Issue by jairideout** [biocore/qiime#1876]
@gregcaporaso, @ebolyen, @shiffer1, and I found a performance bug in split_libraries_fastq.py. It appears to be ~7x slower than QIIME 1.8.0. We think that looping over the numpy array of quality scores returned by `parse_fastq` is causing most of the slowdown.

**Comment by wasade** [comment]
That's interesting, good catch. As @gregcaporaso addressed in #1880, it suggests that there are much more efficient numpy bulk ops that can be performed. I suspect this slowdown stems from the overhead of going back and forth between numpy types where previously it was just pure python.

Was a profile performed here by chance?

**Comment by jairideout** [comment]
Fixed in #1880.
