### ISSUE TITLE
a bug of fraction variance in make_2d_plots.py

### ISSUE THREAD

**Issue by RNAer** [biocore/qiime#1884]
It mistakenly shows fraction as percentage. see the post https://groups.google.com/d/msg/qiime-forum/30-EvCrQotA/0Mbqc0qJ8-UJ
It occurs in 1.9 rc2 and rc1

**Comment by ebolyen** [comment]
@RNAer I am unable to reproduce this. What was the exact command used, and can you email or dropbox me the files used (my email is in my profile)?

**Comment by ElDeveloper** [comment]
I think this is referring to https://github.com/biocore/scikit-bio/issues/563

**Comment by RNAer** [comment]
```
beta_diversity.py -i otu_table.biom -m euclidean -o bd
principal_coordinates.py -i bd/euclidean_otu_table.txt -o bd/euclidean_pc.txt  
make_2d_plots.py -i bd/euclidean_pc.txt -o /tmp/foo4 -m Fasting_Map.txt
```
Files are at https://www.dropbox.com/s/cqa1gq1vzgcnhyz/test.tgz?dl=0

**Comment by ebolyen** [comment]
@RNAer Thanks! I am able to replicate the issue. It looks like it is a disagreement about what `Proportion explained` means. I'll investigate further.
