### ISSUE TITLE
Update QIIME virtual box documentation

### ISSUE THREAD

**Issue by AmandaBirmingham** [biocore/qiime#1900]
Hi--I am new to QIIME and have recently been spending oodles of time with the documentation :) , starting with that associated with the QIIME virtual box. In the process, I noticed a few typos and points where it appears some updates/corrections could help.  I have annotated the relevant files; since GitHub won't let me upload non-image files, I've put them on dropbox at the following links: 

1.Welcome.txt file notes: https://www.dropbox.com/s/fgb92hxdg230p7s/1.Welcome.txt%20notes.pdf?dl=0
3.Getting_started_with_QIIME.txt notes: https://www.dropbox.com/s/l8mqked2beik2z6/3.Getting_started_with_QIIME.txt.pdf?dl=0

Thanks for putting all this documentation together in the first place :)
Amanda

**Comment by jairideout** [comment]
Thanks @AmandaBirmingham! We'll work on integrating these changes for the 1.9.0 release.

**Comment by gregcaporaso** [comment]
Thanks @AmandaBirmingham, glad to hear you're using QIIME! We'll get these suggestions in for 1.9.0, and there are tons of other updates to the documentation coming with the release, so it should be generally better all around soon. Hope San Diego is treating you well so far!
