### ISSUE TITLE
Allow all pairwise comparisons in compare_categories

### ISSUE THREAD

**Issue by johnchase** [biocore/qiime#1912]
If a column in a mapping file contains more than two groups the user should be able to specify in `compare_categories.py` that statistics for all pairwise comparisons be calculated. This would be useful for instance if the groups in a category were fecal, forehead and palm. In this situation the fecal samples may be driving any statistical differences it would be useful to know that the other groups are not different. Currently the way to do this is to filter the distance matrix with `filter_distance_matrix.py` and the run `compare_categories.py` on that. This means that the user may have to run both scripts multiple times rather than a single script. 

An alternative could be to let the user specify which groups to compare, this would also help avoid possible multiple comparisons issues.

**Comment by jairideout** [comment]
This feature was requested in #431. Closing in favor of that issue.
