### ISSUE TITLE
test_rarefaction.py fails with biom-format 2.1.3 and h5py

### ISSUE THREAD

**Issue by jairideout** [biocore/qiime#1918]
tests/test_rarefaction.py fails with biom-format 2.1.3 and h5py:

```
$ python tests/test_rarefaction.py
.....F
======================================================================
FAIL: test_rarefy_to_list (__main__.FunctionTests)
rarefy_to_list should rarefy correctly, same names
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_rarefaction.py", line 92, in test_rarefy_to_list
    self.assertEqual(res[-1][2], self.otu_table)
AssertionError: 4 x 3 <class 'biom.table.Table'> with 6 nonzero entries (50% dense) != 4 x 3 <class 'biom.table.Table'> with 6 nonzero entries (50% dense)

----------------------------------------------------------------------
Ran 6 tests in 0.463s

FAILED (failures=1)
```

Seen the failure on Jenkins and locally (OS X). If I uninstall h5py and rerun the tests, they pass. This doesn't happen with biom-format 2.1.2.

**Comment by Jorge-C** [comment]
It seems to be related to normalizing [missing metadata](https://github.com/biocore/biom-format/pull/589) so maybe just editing the creation of
```
self.otu_table = Table(self.otu_table_data,
self.taxon_names,
self.sample_names,
observation_metadata=[{}, {}, {}, {}],
sample_metadata=[{}, {}, {}])
```
could be enough.

**Comment by jairideout** [comment]
Thanks! I created an issue to track this bug (https://github.com/biocore/biom-format/issues/594). @gregcaporaso and I don't think this is release-blocking since this isn't something that should happen during normal use of QIIME (it only happens in a unit test, which we will update now).
