### ISSUE TITLE
gitter as a possible discussion forum?

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/qiime#1932]
[Gitter](https://gitter.im/) looks really interesting, has anyone used this? It might be something to think about as we're in the process of re-thinking how we provide technical support (#1926). 

[Here](https://gitter.im/ipython/ipython/help) is how IPython uses it.

**Comment by ebolyen** [comment]
It looks like IRC, just a web interface instead (with markdown and latex!). These are pretty common for developer tools, so it might make a lot of sense for scikit-bio, but I'm not sure qiime is the right target for this.

**Comment by wasade** [comment]
Nice: https://irc.gitter.im

No Linux app yet but generally looks awesome

**Comment by gregcaporaso** [comment]
> it might make a lot of sense for scikit-bio, but I'm not sure qiime is the right target

I do think this could make sense as an open developer discussion forum (I didn't really mean to propose it as an alternative to e.g. BioStarts). I'd be happy to have us start testing for scikit-bio as a developer discussion forum. I do think it could be useful for QIIME in that context too (a lot of developer discussion does currently happen over IM).

**Comment by ebolyen** [comment]
That makes a lot of sense. @wasade There is a beta client for debian systems: https://github.com/gitterHQ/desktop

**Comment by wasade** [comment]
:boom:

**Comment by ElDeveloper** [comment]
> 100% compatible with Lynx. Seriously.

They had me at Lynx.

**Comment by gregcaporaso** [comment]
We've started using this, so I'm going to close this issue. Looks like free gitter is working for us for now, but the paid accounts are just too expensive.

**Comment by gregcaporaso** [comment]
I posted [this](https://twitter.com/gregcaporaso/status/573837053353332741), let's see if they respond.

**Comment by gregcaporaso** [comment]
Ask and you shall receive, we now have free Gitter Silver Plan for life for all biocore projects.
