### ISSUE TITLE
hardcoded /tmp directory using mothur taxonomic assigner

### ISSUE THREAD

**Issue by ekopylova** [biocore/qiime#1935]
There are a few threads like [this](https://groups.google.com/forum/#!searchin/qiime-forum/pick_open_reference_otus.py$20error$20deni/qiime-forum/p2iM02MCKi0/x1ewsB2oxh4J) one that fail to assign taxonomy using mothur because of no writing permissions to /tmp directory which appears to be hardcoded in the burrito-fillings mothur API.

More specifically, the 'temp_dir' in QIIME config seems to be ignored and if the TMPDIR env variable is set, only 2/3 paths in the mothur command use that directory. For example, if I set temp_dir in the QIIME config and TMPDIR to /scratch/Users/evko1434/tmp/, the mothur call still uses '/tmp' for the "fasta=" input file).

['mothur', '#classify.seqs(fasta=/tmp/tmplR7bIdnOnVsNxanKAW22.fasta, reference=/scratch/Users/evko1434/tmp/tmpAT0uS4.ref.fa, taxonomy=/scratch/Users/evko1434/tmp/tmpiWOkFe.tax.txt, cutoff=80)']

In /burrito-fillings/bfillings/mothur.py, the input fasta file path is determined using the command: 

        self._input_filename = self.getTmpFilename(suffix='.fasta')

The self.getTmpFilename() function can also accept a tmp_dir argument and by default it is set to '/tmp'. In the case of the command above, no alternative is given to set the temporary directory and it always defaults to '/tmp'.

Both files for "reference=" and "taxonomy=" use NamedTemporaryFile() from tempfile to create temporary files which uses the temporary directory set by $TMPDIR, so no issues there.

**Comment by gregcaporaso** [comment]
@jairideout, this may have been addressed by #1999 - could you check when you get a chance?

**Comment by kylebittinger** [comment]
Looks like a two line fix in burrito-fillings, plus a new test to verify.  I can put this in tomorrow if needed.

**Comment by kylebittinger** [comment]
Pull request is in for fix in burrito-fillings:
https://github.com/biocore/burrito-fillings/pull/61

We need to make a small modification to the calling code in QIIME, described in the pull request.
