### ISSUE TITLE
split_libraries_fastq.py not-barcoded option not sufficiently documented

### ISSUE THREAD

**Issue by adamrp** [biocore/qiime#1940]
There is no mention of it in the description of the `--barcode_type` option, and the usage example uses an option called `--sample_id`, but that is incorrect since the option is actually called `--sample_ids`.  I'm not sure why the usage tests are not failing there.

**Comment by colinbrislawn** [comment]
Hello @adamrp,

The `--barcode_type` option is near the bottom of the list on this page:
http://qiime.org/scripts/split_libraries_fastq.html

I'm looking into the discrepancy with the spelling of `--sample_id`... not sure which is right.

**Comment by jairideout** [comment]
@colinbrislawn that's really interesting! It looks like QIIME allows truncated option names, as long as they aren't ambiguous.

For example, `--sample_i` also works:

```
$ split_libraries_fastq.py -i lane1_read1.fastq.gz,lane2_read1.fastq.gz --sample_i my.sample.1,my.sample.2 -o slout_not_multiplexed_q20/ -q 19 --barcode_type 'not-barcoded'
$
```

But we get an error message with `--s` because it's ambiguous:

```
$ split_libraries_fastq.py -i lane1_read1.fastq.gz,lane2_read1.fastq.gz --s my.sample.1,my.sample.2 -o slout_not_multiplexed_q20/ -q 19 --barcode_type 'not-barcoded'
Error in split_libraries_fastq.py: ambiguous option: --s (--sample_ids, --sequence_max_n, --sequence_read_fps, --start_seq_id, --store_demultiplexed_fastq, --store_qual_scores?)

If you need help with QIIME, see:
http://help.qiime.org
```

Never knew about this feature, very cool! We'll fix the usage examples (even though they technically work) so that `--sample_ids` is used. We'll also document the "not-barcoded" option.

**Comment by ElDeveloper** [comment]
Woow ... I didn't know that either ...

**Comment by colinbrislawn** [comment]
Well... that's just odd.

>It looks like QIIME allows truncated option names
> Never knew about this feature,

I'm not sure if I would consider this a feature @jairideout... Inconsistency makes programs harder to understand, document, and use. This 'flexibility' with mangled option flags could come back to bite qiime users. Imagine a pipeline using a truncated option, which is then rendered ambiguous by the addition of another similarly named option to the surprise of the qiime users.

Maybe we should disable this 'functionality' as described [here on stack exchange](https://stackoverflow.com/questions/1885161/how-can-i-get-optparses-optionparser-to-ignore-invalid-options).

**Comment by gregcaporaso** [comment]
I don't think we should promote its use, but given that we're switching to click for all CLIs, I don't think it's worth investing the effort in explicitly disallowing it.

**Comment by gregcaporaso** [comment]
@ElDeveloper, @jairideout, @colinbrislawn, following on the discussion of truncated option names, [click explicitly does not support that](http://click.pocoo.org/4/why/#why-no-auto-correction), so in QIIME 2 and all other click-based CLIs that we develop we won't have support for that, which I agree is the better way to go. For now, we should just not promote it's use at all, but not go through the effort of explicitly disallowing it.

**Comment by colinbrislawn** [comment]
:+1:
