### ISSUE TITLE
Documentation on biplots

### ISSUE THREAD

**Issue by mortonjt** [biocore/qiime#1944]
I've been looking at the `biplots.py` code and I'm not understanding the math.

Typically a biplot is generated through a SVD - of course we don't have this luxury since the OTU information is lost when calculating the distance matrix.  Looks like in this code, taxa ratios are calculated and multiplied by the PCoA eigenvectors from the distance matrix.

I'm not completely convinced that this is correct.  I realize that this is really legacy code, but if there are any references supporting this math, that would be awesome!  I think I can write up some code to help better interpret these plots once I understand how these coordinates are being calculated

**Comment by ElDeveloper** [comment]
CCing @danknights and @justin212k.

**Comment by justin212k** [comment]
I don't remember the biplot-on-pcoa reference. I do think it's useful sometimes, but afaik pretty unrelated to the biplots made from PCA / SVD analysis.

**Comment by danknights** [comment]
Unfortunately there was no reference for this. We used the weighted average of the coordinates of the samples containing a given bug to obtain the coordinates for that bug, where the relative weights were the relative abundances in the samples. Biplots can also be made directly from correspondence analysis.

**Comment by rob-knight** [comment]
The "usual" way of making them is from PCA, but with PCoA there aren't direct factor loading in taxon space hence the solution Dan describes.


On Mar 1, 2015, at 2:04 PM, danknights <notifications@github.com<mailto:notifications@github.com>> wrote:


Unfortunately there was no reference for this. We used the weighted average of the coordinates of the samples containing a given bug to obtain the coordinates for that bug, where the relative weights were the relative abundances in the samples. Biplots can also be made directly from correspondence analysis.

**Comment by mortonjt** [comment]
I think @danknights may be referring to [distance biplots](http://biol09.biol.umontreal.ca/PLcourses/Legendre_Canonical.pdf) in the context of canonical analysis.

This is great!  Thanks for quick response @justin212k , @danknights !

**Comment by danknights** [comment]
Thanks. Actually I was referring to correspondence analysis biplots like on page 10 here: http://cc.oulu.fi/~jarioksa/opetus/metodi/vegantutor.pdf.
