### ISSUE TITLE
virtual box guest additions install instructions are out of date

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/qiime#1946]
These are now posted on the wiki [here](https://github.com/biocore/qiime/wiki/QIIME-Virtual-Box:-Before-you-start), but are outdated. It's not possible to install the guest additions following the current instructions.

Can someone volunteer to update that wiki page?

cc @antgonza @josenavas

**Comment by antgonza** [comment]
The wiki has been updated. Please take a look - @jairideout and @gregcaporaso.

**Comment by gregcaporaso** [comment]
I've reviewed and tested the instructions, these are good to go now.
