### ISSUE TITLE
split libraries needs support for simple error correction

### ISSUE THREAD

**Issue by alk224** [biocore/qiime#1961]
Right now only 12 base golay codes are corrected.  Many people use indexes of lengths different from these and may need simple error correction (some number of allowed mismatches).  In practice, I have seen no real benefit to using 12 base golay codes over standard 6-base codes used by Illumina or 8 base codes that I designed myself.  I suspect this benefit has dramatically diminished with the advent of Illumina data over 454 due to the types of errors incurred (substitution versus indel).

**Comment by alk224** [comment]
Might be related to the issue here: https://github.com/biocore/qiime/issues/1954

I promise I searched, but nothing came up!

**Comment by josenavas** [comment]
Hi @alk224 

Not all barcodes can be corrected. See more information about error correcting barcodes and the advantages of using golay 12 in these two papers:

http://www.ncbi.nlm.nih.gov/pubmed/18264105
http://www.ncbi.nlm.nih.gov/pubmed/22402401

**Comment by alk224** [comment]
@josenavas The Hamady paper definitely addresses this, but in a way that isn't entirely accessible to me as it masks the biological advantages in a bunch of computer science jargon (hypersphere, what??).  I used only 12 base Golay codes (different I think than the Hamming approach, but not certain) for quite a while, and then had to do some nextera preps which use dual 6 base codes.  The Illumina demultiplexer takes a far simpler approach and simply allows a single mismatch per index.  As long as the codes are at least 2bp distant from one another, every code can be corrected.  So just like with Golay/Hamming codes, if your choice of allowable error is within the distance specified by the code set, you can set an allowable number of mismatches and not have any problems.

Of far more concern to me is the use of single indexing which should absolutely be phased out.  Single indexing allows infiltration of phix sequences into sample data at surprisingly high levels (I've seen as high as 8%, dependent on cluster density and % spike in).  This implies that sample sequences may be incorrectly attributed (lower percentage than phix which is "dark" during index cycles) to the wrong index sequence, and in fact was shown to be the case by Kircher et al way back in 2012 (http://www.ncbi.nlm.nih.gov/pubmed/22021376).  Due to the surprising rate of sequence misattribution simply by use of single indexing, it is a wonder more people haven't abandoned them sooner, and this is a problem that Golay coding cannot solve.

**Comment by yech1990** [comment]
It is a year passed.
Does this request be added to the repository?

**Comment by gregcaporaso** [comment]
@yech1990, thanks for following up. We're currently not adding any new features to QIIME 1 as we focus our development efforts on [QIIME 2](https://qiime2.org). If there is a demultiplexing format that you would like to see support for (same goes for you of course, @alk224), would you be willing to post an issue on the [q2-demux issue tracker](https://github.com/qiime2/q2-demux/issues)? 

Sorry that this won't be added to QIIME 1.
