### ISSUE TITLE
filter_taxa_from_otu_table.py uninformative error

### ISSUE THREAD

**Issue by wdwvt1** [biocore/qiime#1963]
When attempting to filter an OTU table down to only a specific taxonomy string (`-p` option), if the taxonomy is not found the script will error with a non-informative message. It will also create a malformed HDF5 table in the specified output location. 

Here is an example that creates a small table that produces the error:
```python
from numpy import array
from biom.table import Table
from h5py import File
data = array([[1,2,3],[4,5,6]])
oids = ['otu1', 'otu2']
sids = ['s1', 's2', 's3']
md = [{'taxonomy': ['k__bacteria','p__firmicutes']}, {'taxonomy':['k__eukaryotes', 'p__something']}]
bt = Table(data, oids, sids, observation_metadata=md)

o = File('/Users/wdwvt/Desktop/ex.biom', 'w')
bt.to_hdf5(o, 'example')
o.close()
```

Then, attempt to filter with
```bash
filter_taxa_from_otu_table.py -i /Users/wdwvt/Desktop/ex.biom -p 'something_not_in_there' -o /Users/wdwvt/Desktop/ex.f.biom
```
Errors with:
```bash
Traceback (most recent call last):
  File "/Users/wdwvt/src/qiime/scripts/filter_taxa_from_otu_table.py", line 85, in <module>
    main()
  File "/Users/wdwvt/src/qiime/scripts/filter_taxa_from_otu_table.py", line 81, in main
    write_biom_table(input_table, output_table_fp)
  File "/Users/wdwvt/src/qiime/qiime/util.py", line 555, in write_biom_table
    biom_table.to_hdf5(biom_file, generated_by, compress)
  File "/Users/wdwvt/src/biom-format/build/lib.macosx-10.5-x86_64-2.7/biom/table.py", line 3481, in to_hdf5
    self.group_metadata(axis='observation'), 'csr', compression)
  File "/Users/wdwvt/src/biom-format/build/lib.macosx-10.5-x86_64-2.7/biom/table.py", line 3450, in axis_dump
    for category in md[0]:
IndexError: tuple index out of range
```

**Comment by ElDeveloper** [comment]
@wdwvt1, I was able to reproduce the bug, and I think I found the
culprit. See the links below. (1) biom's err.py module tags the check
for "empty tables" as errors that can be "ignored" and (2) even if that
was not the case the raised error is pretty bad from the context of a
QIIME script.

```
  File "/Users/yoshikivazquezbaeza/.virtualenvs/qiime-dev/bin/filter_taxa_from_otu_table.py", line 10, in <module>
    execfile(__file__)
  File "/Users/yoshikivazquezbaeza/git_sw/qiime/scripts/filter_taxa_from_otu_table.py", line 87, in <module>
    main()
  File "/Users/yoshikivazquezbaeza/git_sw/qiime/scripts/filter_taxa_from_otu_table.py", line 79, in main
    input_table.filter(filter_fn, axis='observation')
  File "/Users/yoshikivazquezbaeza/.virtualenvs/qiime-dev/lib/python2.7/site-packages/biom/table.py", line 1869, in filter
    errcheck(table, 'empty')
  File "/Users/yoshikivazquezbaeza/.virtualenvs/qiime-dev/lib/python2.7/site-packages/biom/err.py", line 473, in errcheck
    raise ret
biom.exception.TableException: Empty table!
```

https://github.com/biocore/biom-format/blob/master/biom/err.py#L322
https://github.com/biocore/biom-format/blob/master/biom/table.py#L1872

I've opened an issue in biom to see if this was an intended behavior
(and applications like QIIME have to change this at the global state) or
a bug.

https://github.com/biocore/biom-format/issues/619

**Comment by wasade** [comment]
One fix is for qiime to use bioms seterr and set empty='raise'

**Comment by ElDeveloper** [comment]
Yeah, so probably this should be done at the module level?

**Comment by wasade** [comment]
I think so

**Comment by ElDeveloper** [comment]
If others agree to this solution, I can try putting it in place, but
since it affects the behavior of the whole package, I would rather be
cautious about it.

**Comment by wasade** [comment]
you can encapsulate it

```python
with seterr(empty='raise'):
    # do stuff
```

**Comment by ElDeveloper** [comment]
:boom:, yes that can be done, but then should that be done on a
case-by-case basis or at the module level. I don't think we've
historically allowed empty tables in QIIME (of course this could
change), so maybe doing it at the module level would make more sense.

**Comment by jairideout** [comment]
@gregcaporaso and I modified `qiime.util.write_biom_table` so that an exception is raised telling users that QIIME doesn't support writing empty BIOM tables to disk. We created a new exception type, `EmptyBIOMTableError`, which inherits from `biom.exception.BiomException`, in case other places in QIIME need to raise this same type of error. This exception type is also easily catchable. In filter_taxa_from_otu_table.py, we are catching the error and providing a more specific error message to users.

**Comment by ElDeveloper** [comment]
This sounds good!

**Comment by gregcaporaso** [comment]
Just for the record, here's what the error messages look like now from the three OTU table filtering scripts in QIIME:

```bash
$ filter_samples_from_otu_table.py -i ex.biom -o ex.o.biom -n 10000000
Error in filter_samples_from_otu_table.py: Filtering resulted in an empty BIOM table. This indicates that no samples remained after filtering.

If you need help with QIIME, see:
http://help.qiime.org

$ filter_taxa_from_otu_table.py -i ex.biom -p 'something_not_in_there' -o ex.f.biom
Error in filter_taxa_from_otu_table.py: Filtering resulted in an empty BIOM table. This indicates that no OTUs remained after filtering.

If you need help with QIIME, see:
http://help.qiime.org

$ filter_otus_from_otu_table.py -i ex.biom -o ex.o.biom -n 10000000
Error in filter_otus_from_otu_table.py: Filtering resulted in an empty BIOM table. This indicates that no OTUs remained after filtering.

If you need help with QIIME, see:
http://help.qiime.org
```

**Comment by Casey779** [comment]
> Just for the record, here's what the error messages look like now from the three OTU table filtering scripts in QIIME:
> 
> ```shell
> $ filter_samples_from_otu_table.py -i ex.biom -o ex.o.biom -n 10000000
> Error in filter_samples_from_otu_table.py: Filtering resulted in an empty BIOM table. This indicates that no samples remained after filtering.
> 
> If you need help with QIIME, see:
> http://help.qiime.org
> 
> $ filter_taxa_from_otu_table.py -i ex.biom -p 'something_not_in_there' -o ex.f.biom
> Error in filter_taxa_from_otu_table.py: Filtering resulted in an empty BIOM table. This indicates that no OTUs remained after filtering.
> 
> If you need help with QIIME, see:
> http://help.qiime.org
> 
> $ filter_otus_from_otu_table.py -i ex.biom -o ex.o.biom -n 10000000
> Error in filter_otus_from_otu_table.py: Filtering resulted in an empty BIOM table. This indicates that no OTUs remained after filtering.
> 
> If you need help with QIIME, see:
> http://help.qiime.org
> ```

Hello,

I recently received the error message listed above (Error in filter_otus_from_otu_table.py: Filtering resulted in an empty BIOM table. This indicates that no OTUs remained after filtering). I have been unable to complete pick_open_reference_otus as I receive an error massage that my fasta file was empty during the filter_alignment.py. I backtracked and found that in the pynast_aligned_seqs folder my rep_set_aligned.fasta is empty. I inputted

filter_otus_from_otu_table.py -i otu_table_mc2_w_tax.biom -o otu_table_mc2_w_tax_no_pynast_failures.biom -e pynast_aligned_seqs/rep_set_failures.fasta

To try and create the otu_table_mc2_w_tax_no_pynast_failures.biom I needed, and this is where I received the error message that the filtering resulted in an empty BIOM table. Would anyone know how to possibly remedy this?
I'm sorry, this is just my first time using QIIME and doing any bioinformatics so I'm suck. Thank you for any help you can offer.

-Darryl

**Comment by gregcaporaso** [comment]
Hi @Casey779, [QIIME 1 isn't supported anymore](https://qiime.wordpress.com/2018/01/03/qiime-2-has-succeeded-qiime-1/). We strongly recommend that you switch over to [QIIME 2](https://qiime2.org). You could post this question to the [QIIME 1 forum](http://forum.qiime.org), but we don't regularly monitor or reply to posts anymore (though sometimes other community members will reply). We do actively support QIIME 2, so you can feel free to get in touch with QIIME 2 questions on the [QIIME 2 Forum](https://forum.qiime2.org) - we strive to reply to those within a couple of working days.

**Comment by Casey779** [comment]
Hi,
I will try to post it on the QIIME 1 forum, thank you!
I am using QIIME 1.9.1 currently as the student before me used QIIME 1.9.1 for their analysis and I am currently just fitting in a piece of data/new sample to their previous analysis. Upon this projects completion I will begin to learn QIIME 2.
