### ISSUE TITLE
add note to AWS tutorial about correct user to run commands as

### ISSUE THREAD

**Issue by jairideout** [biocore/qiime#1966]
@adamrp ran into an issue with matplotlib when using the QIIME 1.9.0 AMI to execute the Illumina overview tutorial. It turns out that commands need to be run as the `ubuntu` user, otherwise matplotlib won't find the correct matplotlib config file to load (which sets the Agg backend).

This applies to running commands directly on an instance (e.g., by ssh-ing in) or via an IPython Notebook server. For the former, the user needs to log in as `ubuntu`. For the latter, the IPython Notebbok server needs to be started by the `ubuntu` user, such that executing `!whoami` in a notebook returns `ubuntu`.

The current [AWS tutorial](http://qiime.org/tutorials/working_with_aws.html) references the `ubuntu` user in several of the commands but doesn't explicitly state this requirement anywhere. It'd be helpful to update this document to make this requirement clearer.

**Comment by gregcaporaso** [comment]
Thanks @jairideout!

**Comment by gregcaporaso** [comment]
This will go live with the 1.9.1 docs: 

![screenshot 2015-05-01 11 17 48](https://cloud.githubusercontent.com/assets/192372/7434945/be00868c-eff3-11e4-8b81-7385c5f7810f.png)
