### ISSUE TITLE
Idea about CLI handling

### ISSUE THREAD

**Issue by mortonjt** [biocore/qiime#1968]
I just had a very crazy idea.

What if we have command line interface scripts built during the installation process?
When `python setup.py build` is called, some script will be called and will parse all of the numpy doc strings in the file. Those functions with doc strings that have some sort of build specification will be used as the main function in the generated scripts.

This will ultimately allow for
* Less maintenance - Maintaining many scripts and it can be a bear to maintain I imagine.  This procedure will only require the doc strings to be modified, and the scripts will follow from there.  
* Maintainable documentation on command line arguments through the doc strings
* More streamlined testing
* Accessible API tied in with CLI

Its probably a little late in the game to implement with QIIME, but maybe with QIIME2?

**Comment by josenavas** [comment]
Hi @mortonjt 

That is not a crazy idea. It has been deeply discussed and it is a main goal of QIIME2. However, numpy documentation is not likely enough, and we came up with a type system definition. @ebolyen and @jairideout have a demo about the typing system.

I already have base code that will work to do this :-)

**Comment by mortonjt** [comment]
:+1:

**Comment by mortonjt** [comment]
Didn't know about that.  Very cool!  I would like to see that demo sometime.  Maybe we can do something similar in Emperor

**Comment by wasade** [comment]
To expand, it was discussed [here](https://hackpad.com/Biocore-summit-14_12-Flagstaff-QIIME-2.0-code-sprint-VzNyOoIJkWd#:h=Plugin-system-discussion). What we want to do is avoid parsing and inferring. The draft implementation (at least back in Flagstaff, and I realize this is totally influx) made heavy use of decorators. The beauty of it was that we could trivially generate numpydoc, as well as get all the benefit of typing, etc. To show you what it kind of looked like (from memory):

```python
@shortdef("This thing does all the magic")
@parameter(name="foo", type=int, help="This does this does this", default=5, required=False)
@parameter(name="bar", type=Range(1,10), help="This does this other thing")
@raises(KeyError, when="foo violates bar")
@returns(int, help="the result of foo and bar")
@returns(generator, help="why not")
def your_function(**kwargs):
    # ...
```

The explicit annotation allows us to request all these bits trivially and construct interfaces at will. 

...and again, the above is not exactly what we had been toying around with but is a rough approximation of one possible way forward.

**Comment by mortonjt** [comment]
Thanks!
