### ISSUE TITLE
install sourcetracker 1.0 in virtual machines

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/qiime#1976]
This doesn't require any code changes in QIIME, just installing a different version into the virtual machines.

**Comment by jairideout** [comment]
This change should happen in qiime-deploy-conf so that the VirtualBox and AMI both get this installed automatically and qiime-deploy users also get the same version of SourceTracker.

**Comment by jairideout** [comment]
@antgonza are you available to work on this one? I think the only changes are updating the sourcetracker target in qiime-deploy-conf.

**Comment by antgonza** [comment]
@jairideout and @gregcaporaso, what do you think is best here? (1) modify the 1.9.0 script or (2) create a 1.9.1 script and make modification there?

**Comment by gregcaporaso** [comment]
1.9.1 I think, but the change should only be in qiime-deploy-conf, right?

**Comment by antgonza** [comment]
yup

**Comment by antgonza** [comment]
Did it again! Pointed to the wrong issue: https://github.com/qiime/qiime-deploy-conf/pull/144
