### ISSUE TITLE
Update dependency to BIOM 2.1.4 (bugfix release)

### ISSUE THREAD

**Issue by wasade** [biocore/qiime#1977]
I'm a terrible human being for not having this out yet.

**Comment by gregcaporaso** [comment]
@wasade, do you have an ETA for the release? I assume that we'll want this version inclused in the 1.9.1 virtual machines?

**Comment by wasade** [comment]
Wednesday, that work?

**Comment by gregcaporaso** [comment]
That'd be perfect, thanks!

**Comment by gregcaporaso** [comment]
Just for the record, this will address biocore/biom-format#599 (correct me if I'm wrong about that please @wasade).
