### ISSUE TITLE
glitch in documentation of script multiple_rarefactions.rst

### ISSUE THREAD

**Issue by qingpeng** [biocore/qiime#1988]
https://github.com/biocore/qiime/blob/master/doc/scripts/multiple_rarefactions.rst

The long form of an options "-n" is "--num-reps" actually, but in the documentation it is listed as "--num_reps".

**Comment by jairideout** [comment]
The option name was changed to `--num_reps` in QIIME 1.9.0, so this documentation is correct. To see documentation for older versions of QIIME, for example, 1.8.0:

http://qiime.org/1.8.0
