### ISSUE TITLE
updates to support new version of burrito-fillings

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/qiime#2000]
- [x] update minimum version of ``bfillings`` and ``burrito`` in setup.py
- [x] https://github.com/biocore/qiime/issues/2004
- [x] https://github.com/biocore/qiime/issues/1935

**Comment by gregcaporaso** [comment]
Sweet, issue #2000!!

**Comment by jairideout** [comment]
- [ ] verify GitHub doesn't have Y2K bug

**Comment by gregcaporaso** [comment]
I think you mean *I2K* (issue 2000)

**Comment by jairideout** [comment]
Good catch, thanks!

**Comment by ElDeveloper** [comment]
![](http://bestanimations.com/Holidays/Fireworks/Fireworks-01-june.gif)

**Comment by jairideout** [comment]
![image](https://cloud.githubusercontent.com/assets/1847232/7434390/5e94b4d8-efef-11e4-9a51-9849d31c2fad.png)
