### ISSUE TITLE
filter_samples_from_otu_table.py can no longer generate filtered mapping file

### ISSUE THREAD

**Issue by Nan-Shen** [biocore/qiime#2003]
In old QIIME version 1.8.0, it used to be able to generate a filtered mapping file after passing "-m" and "--output_mapping_fp" with "-n", "-x" or "--sample_id_fp". Now in 1.9.0, unless I use "--valid_states", it will give an error message if "-m" is passed.

**Comment by gregcaporaso** [comment]
@Nan-Shen, thanks for reporting this. It will be fixed in the upcoming 1.9.1 release.
