### ISSUE TITLE
bottom text box colors not matching legend in make_rarefaction_plots.py

### ISSUE THREAD

**Issue by walterst** [biocore/qiime#2007]
The colors in the legend will fail to match the samples in the bottom text box under certain circumstances (see https://groups.google.com/forum/#!searchin/qiime-forum/Alpha$20rarefaction$20plot$20(Qiime$201.9.0)/qiime-forum/yRVgxPx7dPA/xCRB8MTUl4oJ).

To replicate the issue, there has to be duplicate values in metadata fields for different columns in the mapping file.

One can duplicate this by downloading these files:
https://www.dropbox.com/s/cscnif7o2y32oz8/Fasting_Map_modified2.txt?dl=0
https://www.dropbox.com/s/lnprmyip7s548f4/alpha_div_collated.zip?dl=0

And running this command:
make_rarefaction_plots.py -m ../Fasting_Map_modified2.txt -i alpha_div_collated/ -o alpha_rarefaction_plots/

The text colors at the bottom of the html page will match the legend (A_cnd1, A_cnd2, AcF_AmF, AcF_AmF_BcF), but the coloration no longer matches with AcF_BcF, which has the same duplicate metadata field values as some of the prior metadata categories.

**Comment by walterst** [comment]
After digging through the code a bit, this seems to be where the incorrect colors are being assigned to the metadata category keys:
https://github.com/biocore/qiime/blob/master/qiime/make_rarefaction_plots.py#L734

**Comment by gregcaporaso** [comment]
@antgonza or @ElDeveloper, are you available to work on this one?

**Comment by antgonza** [comment]
Added a solution in https://github.com/biocore/burrito-fillings/pull/66

**Comment by jairideout** [comment]
I don't think this issue was addressed in your burrito-fillings PR because make_rarefaction_plots.py doesn't wrap any external applications.

**Comment by antgonza** [comment]
Yeah, just got the wrong number on my commit ...

**Comment by jairideout** [comment]
Not fixed, reopening...

**Comment by jairideout** [comment]
woops, got confused by github saying it was closed in  gregcaporaso/burrito-fillings@a8b8e1d 

Sorry!!

**Comment by jairideout** [comment]
Need... more... coffee... this should be closed when https://github.com/biocore/qiime/pull/2023 is merged. Reopening
