### ISSUE TITLE
.imputed rep_set file for pynast_template_alignment_fp

### ISSUE THREAD

**Issue by colinbrislawn** [biocore/qiime#2012]
On this [qiime forum question](https://groups.google.com/forum/#!topic/qiime-forum/qM-ottO7mEE), @Cody-Glickman asked the following question:

>I am attempting to upgrade the greengenes database on a cluster. The current parameters file is using GreenGenes version 13_5 and the pynast_template_alignment_fp is set to a file format ending with a .imputed extension. The file appears to contain some differences from the rep set aligned .fasta file. I have downloaded GreenGenes version 13_8 and the rep_set_aligned files do not contain a .imputed file. Should I simply change the parameters to reference the .fasta file in gg_13_8_otus/rep_set_aligned/ or should I utilize a secondary software such as IMPUTE2 or BEAGLE to impute the file format? 

Thoughts @ElDeveloper, @jairideout?

Any guidance is appreciated!
Colin

**Comment by jairideout** [comment]
Thanks @colinbrislawn! I followed up on the [forum thread](https://groups.google.com/d/topic/qiime-forum/qM-ottO7mEE/discussion). Please post any further discussion there.
