### ISSUE TITLE
Documentation and example for summarize_taxa.py 

### ISSUE THREAD

**Issue by colinbrislawn** [biocore/qiime#2015]
The documentation for summarize_taxa.py uses RDP classifier taxonomy as an example for classification levels. As greengenes is now the default database and had different meaning for each level, this has [confused some users](https://groups.google.com/forum/#!topic/qiime-forum/vKAfHuvr3fA). 

I'll see if I can fix this.

**Comment by gregcaporaso** [comment]
closed in #2016
