### ISSUE TITLE
collapse_samples.py does not collapse .tre files

### ISSUE THREAD

**Issue by colinbrislawn** [biocore/qiime#2057]
The script [collapse_samples.py](http://qiime.org/scripts/collapse_samples.html) will merge/collapse samples in the provided .biom table and metadata file, but will not collapse samples in a phylogenetic tree.

Phylogenetic trees and UniFrac distances are a core part of qiime analysis, so I think this is a very helpful feature.

Colin

**Comment by josenavas** [comment]
Hi @colinbrislawn 

The phylogenetic tree only contains the OTU sequences not the samples itself, so you don't need to collapse them. Does this make sense?

**Comment by colinbrislawn** [comment]
Oh yeah...
This was a dumb issue of me to open. :anguished:

**Comment by josenavas** [comment]
Don't worry @colinbrislawn :smile:
