### ISSUE TITLE
qiime.parse.QiimeParseError: Invalid qual file. Check the format of the qual files.

### ISSUE THREAD

**Issue by hackerzone85** [biocore/qiime#2072]
I am seperate fastq file into fasta and qual file using command
```javascript
$convert_fastaqual_fastq.py -c fastq_to_fastaqual -f seqs.fastq -o fastaqual/ 
```
Then i check the quality distribution over base pairs using command
```javascript
$quality_scores_plot.py -q seqs.qual -o quality_histogram/
```
But above command gives following error [command output]
```javascript
[blab@blab fastaqual]$  quality_scores_plot.py -q SO-3576-MK1_RUN1.qual -o quality_histogram/
Traceback (most recent call last):
  File "/usr/bin/quality_scores_plot.py", line 5, in <module>
    pkg_resources.run_script('qiime==1.9.1', 'quality_scores_plot.py')
  File "/usr/lib/python2.7/site-packages/distribute-0.6.45-py2.7.egg/pkg_resources.py", line 505, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/distribute-0.6.45-py2.7.egg/pkg_resources.py", line 1245, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/qiime-1.9.1-py2.7.egg/EGG-INFO/scripts/quality_scores_plot.py", line 95, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/qiime-1.9.1-py2.7.egg/EGG-INFO/scripts/quality_scores_plot.py", line 91, in main
    qual_parser=parse_qual_score)
  File "/usr/lib/python2.7/site-packages/qiime-1.9.1-py2.7.egg/qiime/quality_scores_plot.py", line 205, in generate_histogram
    qual_scores = qual_parser(qual_lines)
  File "/usr/lib/python2.7/site-packages/qiime-1.9.1-py2.7.egg/qiime/parse.py", line 746, in parse_qual_score
    id_to_qual = dict([rec for rec in MinimalQualParser(infile, value_cast_f)])
  File "/usr/lib/python2.7/site-packages/qiime-1.9.1-py2.7.egg/qiime/parse.py", line 759, in MinimalQualParser
    "Invalid qual file. Check the format of the qual files.")
qiime.parse.QiimeParseError: Invalid qual file. Check the format of the qual files.
```
Structure of qual file
>M02845:20:000000000-ABJ49:1:1101:11123:1164
2 23 32 34 34 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 2 25 34 37 38 37 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38
38 38 38 38 38 38 38 38 2 25 34 37 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 2 25 33 35 37 38 38 38 38 38 38 38 38 38 38 38 38 38 38 35 38 38 38 38 38 38 38 38 38 38
38 38 38 37 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 37 38 37 38 38 35 37 38 38 38 38 38 38 37 38 38 38 38 38 38 38 38 37 37 37 37 35 38 38 38
38 38 38 36 38 34 2 20 31 35 37 37 2 23 31 35 37 38 38 38 37 38 35 37 22 2 18 18 31 22 37 38 38 37 38 2 2 21 21 27 37 38 7 2 17 15 28 31 34 35 33 29 38 37 36 37 37 30 29 38
29 21 2 9 17 25 16 18 36 33 37 37 37 29 8 9 2 15 2 2 2 2 2 2 9 16 12 25 18 25 29 29 8 22 27 29 38 34 29 33 37 37 7 2 2 7 12 12 19 25 10 23 8 18 23 15 27 19 13 2
7
>M02845:20:000000000-ABJ49:1:1101:11604:1170
2 23 33 34 34 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38
38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 2 25 33 28 37 38 38 38 38 38 38 38 38 38 38 38 38 37 38 38 38 38 38 38 38 38 38 38 38 38
38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 35 36 35 38 38 38 38 38 38 38 37 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 24 33 36 33 36 38 37 38 38 38 37
37 38 38 37 37 38 38 38 38 35 38 37 38 38 38 38 38 38 38 37 37 28 35 37 38 37 38 37 34 23 35 38 38 38 22 2 20 31 35 34 37 38 8 28 37 37 38 28 36 24 33 37 35 37 36 37 37 31 37 34
35 12 2 14 17 23 24 33 38 33 35 33 28 35 37 10 2 17 2 8 2 18 7 2 17 17 7 7 21 7 21 31 24 32 20 34 10 15 7 19 24 21 29 15 25 22 25 25 7 7 9 17 20 17 36 32 9 19 13 2
12
.....

**Comment by gregcaporaso** [comment]
This is also more suited for the QIIME Forum. @hackerzone85, note that we answer questions much more quickly there (usually within one working day).
