### ISSUE TITLE
SILVA 111 taxonomy assignment

### ISSUE THREAD

**Issue by DanoneResearch** [biocore/qiime#2076]
Dear Madam, Sir,
For the QIIME-compatible version of SILVA 111, the file '97_Silva_111_taxa_map.txt' seems to contain incorrect taxonomy identifiers; e.g.:
WRONG	Bacteria;__Actinobacteria;__Actinomycetales;__Actinomycetaceae;__Actinomyces;Other
	OK	Bacteria;__Actinobacteria;__Actinobacteria;__Actinomycetales;__Actinomycetaceae;__Actinomyces
Please let me know if you need more information.
Kind regards,
Jolanda.

**Comment by ElDeveloper** [comment]
@DanoneResearch I reached out to the maintainer (@walterst) of this Silva data files and he pointed out that he didn't do any manual curation to the taxonomy strings. Additionally, it seems like this particular instance was corrected in Silva's release 119, so you may want to use those data files instead.

**Comment by DanoneResearch** [comment]
Dear Yoshiki,
Thank you for your fast reply! We will indeed revert tot version 119.
Kind regards, Jolanda.
Op 27 aug. 2015 18:19 schreef "Yoshiki Vázquez Baeza" <
notifications@github.com>:

**Comment by ElDeveloper** [comment]
Great, thanks!
