### ISSUE TITLE
OTU picking help

### ISSUE THREAD

**Issue by kclueneberg** [biocore/qiime#2079]
Hello,

I'm using Qiime for the first, I was following this tutorial but I got stuck on the OTU picking step, I used
pick_open_reference_otus.py -o otus/ -i slout/seqs.fna -p ../uc_fast_params.txt, exactly as it says but I get this error message: 
pick_open_reference_otus.py: error: Required option --reference_fp omitted

What can I do?

Thank you

Regards

Kathia

**Comment by ElDeveloper** [comment]
Hi @kclueneberg, I think you need to add the `-r` option to your command (see the help for `pick_open_reference_otus.py`).

In general, GitHub issues are not the best way to ask for support, the [QIIME forum](http://forum.qiime.org) is a much more powerful platform for that, it is also highly monitored and responses are much quicker than through GitHub. If you have any further questions, please send them to the [QIIME forum](http://forum.qiime.org), else if you have any bug reports or feature requests, then please open a new issue.
