### ISSUE TITLE
Feature Request: splitting demultiplexed fastq.

### ISSUE THREAD

**Issue by zachcp** [biocore/qiime#2082]
Hello Team Qiime,

I would be interested in seeing an option added to the `split_libraries_fastq.py` that would allow you to  to split the demultiplexed file so that there is a single fastq file for each sample. Although, you can split the file on a second pass, it would be nice to move this functionality upstream.

Ideally, if you are using `--store_demultiplexed_fastq`, you could also set a flag for `--split_files` and instead of generating a single fastq file, you would obtain a folder with a fastq-file for each sample.

Thanks,
zach cp

**Comment by antgonza** [comment]
We have something like that implemented for qiita. During split libraries we store both the demux file in fastq and a new file in hdf5 format that contains all the info for in a smaller version (something similar to the new biom format). Then during the generation of EBI we read the demux file in hd5 format and create a per sample files in fastq.gz format. 

I know is not exactly what you are looking for but it could be the code base for this. 

Our of curiosity, why do you need this feature?

**Comment by zachcp** [comment]
@antgonza thanks for the reply.

This came up in the context of kicking the tires on [dada2](https://github.com/benjjneb/dada2) which takes per-sample fastq files. So thats the immediate use-case but I think its a generally usefuI feature. For example, I prefer to store the raw data on a per-sample basis as its easier for reuse - (e.g. if you are only interested in samples A,B &C you can grab the fastq's for only those samples), and also for submission to the SRA/EBI.

I can take a look at Qiita and try it although for my current needs it is straightforward to simply split the demultiplexed files post- `split_library_fastq.py`. Would Qiita benefit from splitting the file by sample? One benefit would be easy per-sample parallelization of the hdf5 creation stage.
