### ISSUE TITLE
Installation interrupts at installing pyqi

### ISSUE THREAD

**Issue by GilEstel** [biocore/qiime#2085]
Hi There,

I'm trying to install qiime on centos. My Problem is, that the installation stops with the following error:

>Collecting pyqi==0.3.2 (from biom-format<2.2.0,>=2.1.4->qiime)
>  Using cached pyqi-0.3.2.tar.gz
>    Complete output from command python setup.py egg_info:
>    Traceback (most recent call last):
>      File "<string>", line 20, in <module>
>      File "/tmp/pip-build-EDuu3q/pyqi/setup.py", line 45, in <module>
>        ver = '.'.join(map(str, [sys.version_info.major, sys.version_info.minor]))
>    AttributeError: 'tuple' object has no attribute 'major'
>    
>    ----------------------------------------
>Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-EDuu3q/pyqi

My installation process was as following:

    # instead of build-essentials
    sudo yum install -y libxml2 libxml2-devel libxslt libxslt-devel
    # instead of python-dev
    sudo yum install python-devel
    # python-pip was already installed

    #asked for during/by the installation process
    sudo easy_install -U distribute
    sudo pip install numpy==1.9.2
    # upgrade pip to the current version 7.1.2
    sudo pip install --upgrade pip

    sudo pip install qiime

Until the last error I could resolve the problems/errors, but I'm stuck here.

Any help very appreciated!

cheers

Nadine

**Comment by wasade** [comment]
Hi Nadine,

What version of Python are you using? This is very odd to see...

Best,
Daniel

**Comment by GilEstel** [comment]
Hi Daniel,

I'm using 
python --version
Python 2.7.8


Best,
Nadine

**Comment by wasade** [comment]
Could you please run and send back the output from the command:

`python -c "import sys; print sys.version_info.major; print sys.version_info.minor"`

What I'm confused about is the exception is indicating something within Python itself isn't working as `version_info` is from its own standard set of modules.

**Comment by GilEstel** [comment]
Hi,

the output of this is following:

    python -c "import sys; print sys.version_info.major; print sys.version_info.minor"
    2
    7

Best,
Nadine

**Comment by GilEstel** [comment]
Hi,

do you have any ideas in the meantime, what the problem might be?

Best,
Nadine

**Comment by GilEstel** [comment]
I found a way to run the installation without error by calling pip directly. It seems to me that there is a version mix up ongoing between pip and python.

    /usr/local/bin/pip2.7 install qiime

Best Nadine

**Comment by wasade** [comment]
That's great to hear! Thank you for posting your solution -- I apologize
for the delayed response on this thread.
