### ISSUE TITLE
qiime installation error

### ISSUE THREAD

**Issue by khalidqiime** [biocore/qiime#2093]
Hi,

I tried to install qiime on a OpenSuse system and I received the following error.
(Note numpy, pypi and pip are installed)

Can some one help me !
***********************************************************************************************************************
>pip install qiime
Collecting qiime
  Using cached qiime-1.9.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-czfhh48r/qiime/setup.py", line 363
        if all([e not in sys.argv for e in 'egg_info', 'sdist', 'register']):
                                                     ^
    SyntaxError: invalid syntax
    
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-czfhh48r/qiime

**Comment by gregcaporaso** [comment]
@khalidqiime, can you please post this question to the [QIIME Forum](http://forum.qiime.org)? That is our primary resource for technical support with QIIME. Thanks!
