### ISSUE TITLE
Link Broken:  Illumina Overview Tutorial IPython Notebook

### ISSUE THREAD

**Issue by xuguang54** [biocore/qiime#2094]
This tutorial is provided as an IPython Notebook. See the Illumina Overview Tutorial IPython Notebook.

**Comment by gregcaporaso** [comment]
Confirmed.

**Comment by gregcaporaso** [comment]
Hmm, it seems to be working for me now. @xuguang54, is it working for you now? I wonder if it's an intermittent issue with nbviewer (the site that is rendering the tutorial). Note that you can also view the tutorial [here](https://github.com/biocore/qiime/blob/1.9.1/examples/ipynb/illumina_overview_tutorial.ipynb) if you're still having trouble.
