### ISSUE TITLE
pick_otus.py using cd-hit method doesn't see the cd-hit-est program

### ISSUE THREAD

**Issue by wolass** [biocore/qiime#2100]
pick_otus.py -i Output/seqs_filtered.fna -m cdhit -o cdhit_otus/ -s 0.97 -n 100
gives me an error:

     burrito.util.ApplicationNotFoundError: Cannot find cd-hit-est. Is it installed? Is it in your path?

I have cd-hit installed under ubuntu Trusty. 
Problem is that my cd-hit package doesn't have a  cd-hit-est command.
The command that i have is cdhit-est. See the difference? :) 

Maybe this is only my issue - I have reinstalled cd-hit using apt-get and this persists.
I was unable to install cd-hit after downloading aand using make command... It gave lots of warnigs 

    cd-hit-est-2d.c++:439:77: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
     if((Clstr_list[i] = new int[ Clstr_no[i] ]) == NULL) bomb_error("Memory");
                                                                             ^
Please advice how should I proceed now? change the cd-hit-est command name in script? and if yes what is the file name?

here is the whole traceback:
    
    Traceback (most recent call last):
    File "/usr/local/bin/pick_otus.py", line 1004, in <module>
    main()
    File "/usr/local/bin/pick_otus.py", line 769, in main
    trie_prefilter=trie_prefilter)
    File "/usr/local/lib/python2.7/dist-packages/qiime/pick_otus.py", line 1097, in __call__
    seqs=seqs, params=cd_hit_params)
    File "/usr/local/lib/python2.7/dist-packages/bfillings/cd_hit.py", line 256, in cdhit_clusters_from_seqs
    app = CD_HIT_EST(WorkingDir=working_dir, params=params)
    File "/usr/local/lib/python2.7/dist-packages/burrito/util.py", line 201, in __init__
    self._error_on_missing_application(params)
    File "/usr/local/lib/python2.7/dist-packages/burrito/util.py", line 468, in _error_on_missing_application
    "Is it in your path?" % command)
    burrito.util.ApplicationNotFoundError: Cannot find cd-hit-est. Is it installed? Is it in your path?

**Comment by gregcaporaso** [comment]
Hi @wolass. This is coming up because you're trying to use an unsupported version of cd-hit. QIIME supports cd-hit version 3.1.1. (We realized that's very old, but we've preferred uclust, swarm, sumaclust, and sortmerna for a while, all of which are installed with QIIME.) If you want to try to have QIIME use the more recent version, you could run ``alias cd-hit-est=cdhit-est``, but that is not something we support so that may or may not work.
