### ISSUE TITLE
Documentation fix: change -f to -i in example for validate_demultiplexed_fasta.py

### ISSUE THREAD

**Issue by AmandaBirmingham** [biocore/qiime#2102]
The example for validate_demultiplexed_fasta.py reads:
validate_demultiplexed_fasta.py -f seqs.fasta -m Mapping_File.txt
but in fact there is no switch -f ; rather, the required switch for the input fasta file path is -i . Proposed fix: delete f, type i at line 24 of /scripts/validate_demultiplexed_fasta.py :)

**Comment by gregcaporaso** [comment]
Thanks, fixed!
