### ISSUE TITLE
parallel_assign_taxonomy_blast.py appears to incorrectly generate the "formatdb" command

### ISSUE THREAD

**Issue by rjohns03** [biocore/qiime#2120]
Hello all, 

I am trying to use the qiime parallel_assign_taxonomy_blast.py script on a supercomputing cluster. Qiime 1.9.1 via pip using the Anaconda python stack. 

I am running the following command: parallel_assign_taxonomy_blast.py -i dataset_3077.dat -o parallel_assign_taxonomy_blast_output -r dataset_3059.dat  -O 8 -t dataset_3058.dat

and all the dataset_####.dat files are in the current working directory.

After a few moments, the fails while running the following command (taken from the full stack trace, which is attached): 
cd "/users/rjohns03/TestIt/qiime/parallel_assign_taxonomy_blast_output/BTA_GkTte_/"; formatdb -l "dataset_3059.dat.log" -o T -n "dataset_3059.dat" -i "dataset_3059.dat" -p F > "/dev/null" 2> "/dev/null"

This command fails because dataset_3059.dat is not located in /users/rjohns03/TestIt/qiime/parallel_assign_taxonomy_blast_output/BTA_GkTte_ but rather in /users/rjohns03/TestIt/qiime

If I make the following changes and rerun it works:

cd "/users/rjohns03/TestIt/qiime/parallel_assign_taxonomy_blast_output/BTA_GkTte_/"; formatdb -l "dataset_3059.dat.log" -o T -n "dataset_3059.dat" -i "../../dataset_3059.dat" -p F > "/dev/null" 2> "/dev/null"

 so it appears to me that this generated command is missing the "../../" before dataset_3059.dat.

Thank you for your time,

[qiime_error.txt](https://github.com/biocore/qiime/files/83373/qiime_error.txt)

**Comment by gregcaporaso** [comment]
Hi @rjohns03. Does calling ``parallel_assign_taxonomy_blast.py`` work if you pass absolute rather than relative file paths? If not, would you mind following up on the QIIME Forum rather than the issue tracker? We try to consolidate our support efforts there.
