### ISSUE TITLE
Newick format hyperlink in the Illumina tutorial does not work

### ISSUE THREAD

**Issue by wasade** [biocore/qiime#2122]
It points to: http://scikit-bio.org/docs/latest/generated/skbio.io.newick.html, which yields 404.

Issue discovered by Elin Videvall

**Comment by colinbrislawn** [comment]
Here is the correct link:
http://scikit-bio.org/docs/latest/generated/skbio.io.format.newick.html 

Link is in this file:
https://github.com/biocore/qiime/blob/master/examples/ipynb/illumina_overview_tutorial.ipynb
