### ISSUE TITLE
errors from script "split_libraries.py", please help!

### ISSUE THREAD

**Issue by Elff0606** [biocore/qiime#2126]
hi qiimers!
I have a problem when running the split_libraries.py, please help, thanks!
the code is as follows, I have no idea how to deal with the error value. 

qiime@qiime-190-virtual-box:~/1$ split_libraries.py -m 050715AP1-mapping2.txt -q qru1.qual -f qru1.fasta -b hamming_8 -L 2000 -o split_library_output
Traceback (most recent call last):
  File "/usr/local/bin/split_libraries.py", line 411, in <module>
    main()
  File "/usr/local/bin/split_libraries.py", line 408, in main
    truncate_ambi_bases=opts.truncate_ambi_bases)
  File "/usr/local/lib/python2.7/dist-packages/qiime/split_libraries.py", line 1359, in preprocess
    (len(f_ids), len(q_ids)))
ValueError: Found 0 ids in fasta file not in qual file, 454876 ids in qual file not in fasta
qiime@qiime-190-virtual-box:~/1$ 

thanks in advance!
Ru

**Comment by colinbrislawn** [comment]
This issue has been addressed on the qiime fourms:
https://groups.google.com/forum/#!topic/qiime-forum/nMFglm4cEVM

Please close.
