### ISSUE TITLE
error of rdp classifier by using assign_taxonomy.py in qiime

### ISSUE THREAD

**Issue by KaiFeng007** [biocore/qiime#2136]
Dear friends,

I want to use assign_taxonomy.py to make rdp classifier species based on GreenGene database.
Then I run the code:
`/usr/lib/qiime/bin/assign_taxonomy.py -i /home/galaxy/user_data/datasets/000/dataset_459.dat -m rdp -t /usr/local/galaxy/galaxy/tools/IEG/RDP/rdp_classifier_2.11/gg_13_8_otus/taxonomy/97_otu_taxonomy.txt -r /usr/local/galaxy/galaxy/tools/IEG/RDP/rdp_classifier_2.11/gg_13_8_otus/rep_set/97_otus.fasta -o rdp_assigned  -c 0.5`

But there was an error for this, like this:

> 1. Traceback (most recent call last):
> 2. File "/usr/lib/qiime/bin/assign_taxonomy.py", line 429, in <module>
> 3. main()
> 4. File "/usr/lib/qiime/bin/assign_taxonomy.py", line 406, in main
> 5. log_path=log_path)
> 6. File "/usr/lib/python2.7/dist-packages/qiime/assign_taxonomy.py", line 864, in __call__
> 7. max_memory=max_memory, tmp_dir=tmp_dir)
> 8. File "/usr/lib/python2.7/dist-packages/bfillings/rdp_classifier.py", line 503, in train_rdp_classifier_and_assign_taxonomy
> 9. tmp_dir=tmp_dir)
> 10. File "/usr/lib/python2.7/dist-packages/bfillings/rdp_classifier.py", line 473, in train_rdp_classifier
> 11. return app(training_seqs_file)
> 12. File "/usr/lib/python2.7/dist-packages/bfillings/rdp_classifier.py", line 315, in __call__
> 13. remove_tmp=remove_tmp)
> 14. File "/usr/lib/python2.7/dist-packages/burrito/util.py", line 284, in __call__
> 15. 'StdErr:\n%s\n' % open(errfile).read())
> 16. burrito.util.ApplicationError: Unacceptable application exit status: 255
> 17. Command:
> 18. cd "/home/fengkai/"; java -Xmx4000M -cp "/usr/local/galaxy/galaxy/tools/IEG/RDP/rdp_classifier_2.2/rdp_classifier-2.2.jar" edu.msu.cme.rdp.classifier.train.ClassifierTraineeMaker -t"/tmp/RdpTaxonomy_ah4Qrz.txt" -s /tmp/tmpTsCzltjvSc4I28M9mSqL.txt -n1 -vversion1 -mcogent -o /tmp/RdpTrainer_SHVTbk > "/tmp/tmpidRxgzrP5KyqAxlJeayZ.txt" 2> "/tmp/tmpbeYtFNHuqcu6j144hMSs.txt"
> 19. StdOut:
> 20. 
> 21. StdErr:
> 22. Usage: java ClassifierTraineeMaker <tax_file> <rawseq.fa> <trainsetNo> <version> <version_modification> <output_directory>
> 23. This program will create 4 output training files to be used by the classifier: 
> 24. bergeyTrainingTree.xml, genus_wordConditionalProbList.txt, logWordPrior.txt and wordConditionalProbIndexArr.txt
> 25. Command line arguments:
> 26. --tax_file contains the hierarchical taxonomy information in the following format:
> 27. taxid*taxon name*parent taxid*depth*rank
> 28. Fields taxid, the parent taxid and depth should be in integer format
> 29. depth indicates the depth from the root taxon.
> 30. Note: the depth for the root is 0
> 31. EX: 44*ROOT*1*0*domain
> 32. --rawseq.fa contains the raw training sequences in fasta format
> 33. The header of this fasta file starts with ">", 
> 34. followed by the sequence name, white space(s) 
> 35. and a list taxon names seperated by ';' with highest rank taxon first.
> 36. Ex: >seq1     ROOT;Ph1;Fam1;G1
> 37. Note: a sequence can only be assigned to the lowest rank taxon.
> 38. --trainsetNo is a integer. It's used to marked the training information.
> 39. --version indicates the version of the hierarchical taxonomy
> 40. Ex: Bacteria Nomenclature
> 41. --version_modification holds the modifcation information of the taxonomy if any
> 42. Ex: Acidobacterium Added
> 43. --output_directory specifies the output directory

The qiime version is 1.9.0 and the rdp classifier version is 2.11, but when I met this problem, I have tried to different version of rdp classifier, including rdp_classifier-2.2, rdp_classifier-2.5, rdp_classifier-2.10.1 and 2.11. But all of these got similar problem like above.

So what should I do next? Someone could help me? Thanks!

**Comment by gregcaporaso** [comment]
Hi @KaiFeng007, Could you please repost your question to the [QIIME Forum](http://forum.qiime.org)? We handle these types of technical support questions there. Thanks!

**Comment by KaiFeng007** [comment]
I have solved it with the helps of technical guys in QIIME Forum.

**Comment by AlbertWuYZ** [comment]
I almost meet the same problem. May I know how do you solve this problem? Thank you so much!

**Comment by gregcaporaso** [comment]
@AlbertWuYZ, can you please post your question to the [QIIME Forum](http://forum.qiime.org)? We try to address these types of technical support questions there, as it's then easier for others to find answers when they have the same questions. Thank you!

**Comment by h170607** [comment]
> I have solved it with the helps of technical guys in QIIME Forum.

@KaiFeng007 Could you please share the link of the anwser in QIIME Forum? I've got the same error.

**Comment by KaiFeng007** [comment]
> > I have solved it with the helps of technical guys in QIIME Forum.
> 
> @KaiFeng007 Could you please share the link of the anwser in QIIME Forum? I've got the same error.

@h170607  Since it is at very long time ago, I really do not remember what I did at that time. Sorry, but asking for help in QIIME Forum is a good choice.
