### ISSUE TITLE
I can't split libraries

### ISSUE THREAD

**Issue by cluzmaria** [biocore/qiime#2137]
I have 16S data from 454 technology. My mapping file is ok but when I tried to split libraries I obtained this error:

Error in split_libraries.py: No filepaths match pattern/name ''. All patterns must be matched at least once.

I don't know what to do!  Can you help me?

**Comment by gregcaporaso** [comment]
Hi @cluzmaria. Would you mind posting this question to the [QIIME Forum](http://forum.qiime.org)? We try to keep our support questions there, and reserve this issue tracker for bug reports and feature requests. Thank you, and thanks for your interest in QIIME!
