### ISSUE TITLE
Problems of run abort  with QIIME Visualizations apps on   Illumina BaseSpace 

### ISSUE THREAD

**Issue by SantoshThapa1** [biocore/qiime#2138]
Hello,

I ran the QIIME Visualizations apps  available on  Illumina BaseSpace to analyze  16SV4 sequence data generated by MiSeq platform.  I successfully ran the "QIIME Preprocessing" app in the BaseSpace. However, my run aborted several times while running the "QIIME Visualization app". The reason of aborting the operation reads "File "/usr/local/lib/python2.7/dist-packages/qiime/parse.py", line 138, in parse_mapping_file     raise QiimeParseError("No data found in mapping file.")
qiime.parse.QiimeParseError: No data found in mapping file."

I am new to work with sequence data analysis. However, I have created a QIIME mapping file and stored in Google Drive and validated with  Keemai.  Can I generate the mapping file without BarCodesequence, the LinkerPrimersequence?  I prepared my mapping file as follows: 
#SampleID (first column)
#BarcodeSequence (i put 5′ Illumina adapter sequence in 2nd column) 
# LinkerPrimerSequence (I put forward primer sequence in 3rd column)
#ReversePrimerSequence (I put 806r modified illumina in 4th column)
#Description (I put sample description in last column) 

Could you please suggest me is there anything wrong with my mapping file set up in Google spreadsheet. 

Thank you.
Santosh

**Comment by ElDeveloper** [comment]
Does the mapping file pass the validation with Keemai? How many samples do you have listed in your mapping file?

In general we use the QIIME forum to provide support, would you mind sending in a post to the forum with your question, I'll follow-up there, you can find the forum here:
https://groups.google.com/forum/#!forum/qiime-forum

**Comment by SantoshThapa1** [comment]
Yes, the mapping file passed the validation with Keemai. There are 3 samples listed in my mapping file.


I tried to post in the QIIME forum, but could not. No idea (will try it again !) !


Thanks,

Santosh


________________________________

**Comment by ElDeveloper** [comment]
@SantoshThapa1, if at all possible can you copy and past the contents of your mapping file here, or at least a subset of them?

**Comment by SantoshThapa1** [comment]
[AFS_Nymphs_data.xlsx](https://github.com/biocore/qiime/files/188595/AFS_Nymphs_data.xlsx)
This is my mapping file.
Thank you.

**Comment by ElDeveloper** [comment]
@SantoshThapa1, thanks for sending that, the problem is that your sample names all start with the `#` sign, and lines starting with a `#` sign are understood as comments, if you change that, this should work just fine. For more information about the format, see this [link](http://qiime.org/documentation/file_formats.html#metadata-mapping-files).

**Comment by SantoshThapa1** [comment]
Thank you S much @EIDeveloper
