### ISSUE TITLE
Run aborted in QIIME Visualization app due to error in make_emperor.py 

### ISSUE THREAD

**Issue by SantoshThapa1** [biocore/qiime#2140]
Hello,

Could anyone please help me on how to address the following error while launching QIIME Visualization app in Illumina BaseSpace. 
 " Error in make_emperor.py: Due to the variation explained, Emperor could not plot at least 3 axes, check the input files to ensure that the percent explained is greater than 0.01 in at least three axes."

Thanks,
Santosh

**Comment by antgonza** [comment]
Hi @SantoshThapa1, for support, please refer to the QIIME forum: https://groups.google.com/forum/#!forum/qiime-forum.
