### ISSUE TITLE
how to change arb format reference database as a reference database for assign.taxonomy.py script?

### ISSUE THREAD

**Issue by LuffyLuffy** [biocore/qiime#2141]
I downloaded an arb reference database for assign taxonomy, how to make them be a fasta file and its corresponding taxonomy txt file to run the script?

Mine data is miseq function gene data, I have run extract the barcode, split_libraries_fastq.py , pick_de_novo_otus.py.

**Comment by gregcaporaso** [comment]
Hi @LuffyLuffy, could you please repost this question to the [QIIME Forum](http://forum.qiime.org). We handle these types of technical support questions there. 

Thanks!
