### ISSUE TITLE
Logging in

### ISSUE THREAD

**Issue by nds2133** [biocore/qiime#2142]
I'm trying to run QIIME on my mac's virtualbox, and there is no longer an option on the screen to log in. How do I do this? (I tried left command+del and it didn't work)

**Comment by colinbrislawn** [comment]
Hello @nds2133 
What does your screen look like? (You can upload a screenshot)

**Comment by gregcaporaso** [comment]
@nds2133, would you mind reposting to the [QIIME Forum](http://forum.qiime.org)? It helps us to consolidate out support efforts there. Thank you!
