### ISSUE TITLE
differential_abundance.py mapping file subcategory/group order in output file

### ISSUE THREAD

**Issue by borax** [biocore/qiime#2154]
I am using the differential_abundance.py tool to test for taxa abundance differences between sample categories, with the metagenomeSeq algorithm. It's great! However, there doesn't seem to be a connection between the subgroups in my mapping file I pass after -x and -y and which of the two subgroups get considered "group 0" and "group 1" in the output file (for the "+samples in group"  and "counts in group" columns). As far as I can tell group 0 vs. 1 is determined by alphabetical/numerical order of the subcategory name? It would be very nice if there was consistency in the output connected to -x and -y, or if what to expect was stated in the documentation somewhere, because the actual subcategory names I include in the command aren't included anywhere in the output file to make a connection with groups 0 and 1. If I missed where it was stated, I apologize. I would just like to be able to easily tell in which subcategory a taxa is enriched.
 
Thanks!

**Comment by gregcaporaso** [comment]
Hi @borax, Could you please post your question to the [QIIME Forum](http://forum.qiime.org)? It helps us to consolidate these types of support questions there. Thanks!
