### ISSUE TITLE
Error messages when normalizing with DESeq2 and CSS

### ISSUE THREAD

**Issue by kathfi** [biocore/qiime#2157]
Dear all,

I wonder if anyone could help me with the following:
I would like to normalize an out.biom table using CSS, and I keep getting the following error message:

Traceback (most recent call last):
File "/usr/local/bin/normalize_table.py", line 157, in
main()
File "/usr/local/bin/normalize_table.py", line 140, in main
normalize_CSS(input_path, out_path, output_CSS_statistics)
File "/usr/local/lib/python2.7/dist-packages/qiime/normalize_table.py", line 38, in normalize_CSS
run_CSS(temp_fh.name, out_path, output_CSS_statistics=output_CSS_statistics)
File "/usr/local/lib/python2.7/dist-packages/qiime/normalize_table.py", line 76, in run_CSS
app_result = rsl(command_args=command_args, script_name='CSS.r')
File "/usr/local/lib/python2.7/dist-packages/qiime/util.py", line 1968, in __call_
(exit_status, command, stdout, stderr))
burrito.util.ApplicationError: Unacceptable application exit status: 1
command: cd "/home/qiime/Desktop/sandlance/alldata/Normalization/"; R --slave --args --source_dir /usr/local/lib/python2.7/dist-packages/qiime/support_files/R -i /tmp/QIIME-normalize-table-temp-table-5uGkcm.biom -o otu_table_silvamod_css.biom -s otu_table_silvamod_css_CSS_statistics.txt < /usr/local/lib/python2.7/dist-packages/qiime/support_files/R/CSS.r
stdout:

stderr:
Loading required namespace: biomformat
Found more than one class "file" in cache; using the first, from namespace 'BiocGenerics'
Found more than one class "file" in cache; using the first, from namespace 'BiocGenerics'
Error in cumNormStatFast(obj) : Warning sample with one or zero features
Calls: CSS -> cumNormStatFast
Execution halted_

I am using an OTU-table that has taxonomy already assigned and samples with <1000 reads excluded, hence I should not have a sample with 1 or 0 features as the message indicates.
Am I overlooking something else? Why does this message persist?

Another issue I am experiencing is with DESeq2, maybe you can help me here, too?
I am executing these 3 commands to normalize, create a .tab file with taxonomy info and then reassign the taxonomy to the normalized file:

biom convert -i otu_table_silvamod.biom -o otu_table_silvamod.tab --to-tsv --header-key taxonomy
normalize_table.py -i otu_table_silvamod.biom -o otu_table_silvamod_deseq.biom -a DESeq2 -z
biom add-metadata -i otu_table_silvamod_deseq.biom -o otu_table_silvamod_deseq_tax.biom --observation-metadata-fp otu_table_silvamod.tab --observation-header OTUID,taxonomy

These commands work, however taxonomy = 0 in all but 1 case in the file “otu_table_silvamod_deseq_tax.biom”. Why may this be the case? I have created PCoA plots, PCA plots, rarefaction curves etc. with the non-rarefied samples and they look fine.

Any help on these two issues would be greatly appreciated.

Many thanks in advance,
Katharina

**Comment by gregcaporaso** [comment]
Can you please post your question to the [QIIME Forum](http://forum.qiime.org)? We try to address these types of technical support questions there, as it's then easier for others to find answers when they have the same questions. Thank you!

**Comment by kathfi** [comment]
Dear Greg,

unfortunately I don't have permission to post in the forum that you indicate, hence maybe it is possible to address this issue here, or let me know how I can gain access?

many thanks 
Katharina

**Comment by gregcaporaso** [comment]
You'll just need to create a Google Groups account or login with an existing Google account.
