### ISSUE TITLE
Python 3 Syntax Error In 1.9.1 Preventing pip3 Install

### ISSUE THREAD

**Issue by Krailon** [biocore/qiime#2158]
When attempting to install Qiime via pip3 (Python3), the following error is encountered:

```
$ pip3 install qiime
Collecting qiime
  Using cached qiime-1.9.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0b3qius7/qiime/setup.py", line 363
        if all([e not in sys.argv for e in 'egg_info', 'sdist', 'register']):
                                                     ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0b3qius7/qiime/
```

This bug was fixed at the end of April: [78cd4eb~setup.py:363](https://github.com/biocore/qiime/commit/78cd4ebb7a64b8a85253571d136608dc5c3c18c3#diff-2eeaed663bd0d25b7e608891384b7298L363)

**Comment by gregcaporaso** [comment]
@Krailon, QIIME 1 is Python 2 only, so I think you may just need to install with pip. You may also be interested in the conda install instructions though, currently linked from [here](https://groups.google.com/d/msg/qiime-forum/DBXuT2nJ1S4/bTEOtktLCAAJ).
