### ISSUE TITLE
SUMACLUST is launched with 1 thread in multi-thread mode

### ISSUE THREAD

**Issue by stevendbrown** [biocore/qiime#2160]
using QIIME 1.9.1, i launch `pick_open_reference_otus.py` with `-aO 12` but `sumaclust` is invoked with the `-p 1` option, ignoring the 12 threads specified by the `-aO 12`.

command used to start `pick_open_reference_otus.py`:

`pick_open_reference_otus.py -i /Vonnegut/20160624_16S/merge_chunk_1/combined_seqs.fna,[...],/Murakami/20160624_16S_combined/merge_chunk_8/combined_seqs.fna -o /Vonnegut/20160624_16S/merged_8_picked_12threads_sortmerna/ -r /home/sdbrown/Downloads/gg_13_8_otus/rep_set/99_otus.fasta -m sortmerna_sumaclust -aO 12`

process observed in `htop` with the `-p 1` switch indicating 1 thread to `sumaclust`:

`sumaclust -f -l -O /Vonnegut/20160624_16S/merged_8_picked_12threads_sortmerna/1/step4_otus/failures_failures_otus.txt -t 0.97 -p 1 -R 1 /tmp/SumaClustExactMatchFilterEQdWwD.fasta`

i tried running `pick_open_reference_otus.py` with `--threads 12` in addition to `-aO 12` but that script throws an error that `--threads` is not a supported argument. i haven't tried with `pick_otus.py`.

apologies if i've misunderstood something deeper or more profound about the software.

**Comment by gregcaporaso** [comment]
@stevendbrown, sorry for the slow reply on this. Can you please post this question to the [QIIME Forum](http://forum.qiime.org)? We try to address these types of technical support questions there, as it's then easier for others to find answers when they have the same questions. We also don't generally monitor the issue tracker for support questions, hence the very delayed reply on this. Thank you!
