### ISSUE TITLE
A problem occurs when use core_diversity_analyses.py

### ISSUE THREAD

**Issue by imleunghl** [biocore/qiime#2163]
Every time I tried to used core_diversity_analyses.py,I get :
RuntimeWarning: The result contains negative eigenvalues. Please compare their magnitude with the magnitude of some of the largest positive eigenvalues. If the negative ones are smaller, it's probably safe to ignore them, but if they are large in magnitude, the results won't be useful. See the Notes section for more details. The smallest eigenvalue is -0.00561989410039 and the largest is 0.353872816381.

I've try the same command in v1.9 qiime virtual box,I get the same warning.
However,when I used this command with the same parameters  in the version 1.8 virtual box,it works.

**Comment by gregcaporaso** [comment]
This is just a warning, so you don't need to worry about it (note that is says that *If the negative ones are smaller, it's probably safe to ignore them*, and that is the case here). Your results should have been generated and will be fine to use.

**Comment by imleunghl** [comment]
thanks.

2016-07-23 6:20 GMT+08:00 Greg Caporaso <notifications@github.com>:
