### ISSUE TITLE
Error in merge_otu_tables.py: No filepaths match pattern/name

### ISSUE THREAD

**Issue by jjandshi** [biocore/qiime#2169]
merge_otu_tables.py -i AttachedFile1.biom,AttachedFile2,AttachedFile3.biom,AttachedFile4,AttachedFile5.biom -o L6_test.biom

Error in merge_otu_tables.py: No filepaths match pattern/name 'otu_table_k__Bacteria_p__Bacteroidetes_c__Bacteroidia_o__Bacteroidales_f__[Paraprevotellaceae]_g__[Prevotella].biom'. All patterns must be matched at least once.

**Comment by gregcaporaso** [comment]
Can you please post your question to the [QIIME Forum](http://forum.qiime.org)? We try to address these types of technical support questions there, as it's then easier for others to find answers when they have the same questions. Thank you!
