### ISSUE TITLE
SWARM and number of reads

### ISSUE THREAD

**Issue by jeandavidgrattepanche** [biocore/qiime#2170]
Greetings,

I think there is something wrong when using SWARM in pick_otu.py. The output table does not consider all the reads.

For example, if I start with 70,000 reads and only 20,000 reads are clustered in OTUs.

I think the issue is that the table report only the seed copy number and not the total reads number in the SWARM OTUs.

For example, an OTU built in Qiime with Swarm represents 2,227 reads and the same OTU represents 8,964 reads in SWARM.

JD

**Comment by gregcaporaso** [comment]
Can you please post your question to the [QIIME Forum](http://forum.qiime.org)? We try to address these types of technical support questions there, as it's then easier for others to find answers when they have the same questions. Thank you!
