### ISSUE TITLE
parallel_assign_taxonomy_blast.py error

### ISSUE THREAD

**Issue by mpachiad** [biocore/qiime#2173]
Hello qiime,

I posted the same issue at the qiime forum but I didn't get an answer.

We have qiime 1.9.1 in our cluster. Parallel_assign_taxonomy_blast.py doesn't seem to be running properly. I do not get an error with the assign_taxonom.py (using -m blast) and I can call formatdb.

Here is the error I get:
parallel_assign_taxonomy_blast.py -i IODP360.fasta_rep_set.fasta  -t SILVA123_QIIME_release/taxonomy/16S_only/99/taxonomy_all_levels.txt -r SILVA123_QIIME_release/rep_set/rep_set_16S_only/99/99_otus_16S.fasta -o parallel_assignment -O 24
Traceback (most recent call last):
  File "/usr/bin/parallel_assign_taxonomy_blast.py", line 117, in <module>
    main()
  File "/usr/bin/parallel_assign_taxonomy_blast.py", line 113, in main
    suppress_submit_jobs=opts.suppress_submit_jobs)
  File "/usr/lib/python2.7/site-packages/qiime/parallel/util.py", line 133, in **call**
    self._precommand_initiation(input_fp, output_dir, working_dir, params)
  File "/usr/lib/python2.7/site-packages/qiime/parallel/assign_taxonomy.py", line 141, in _precommand_initiation
    params['reference_seqs_fp'], output_dir=working_dir)
  File "/usr/lib/python2.7/site-packages/bfillings/formatdb.py", line 121, in build_blast_db_from_fasta_path
    app_result = fdb(fasta_path)
  File "/usr/lib/python2.7/site-packages/burrito/util.py", line 285, in __call__
    'StdErr:\n%s\n' % open(errfile).read())
burrito.util.ApplicationError: Unacceptable application exit status: 3
Command:
cd "/home/mpachiadaki/Qiime/parallel_assignment/BTA_aOIb0_/"; formatdb -l "99_otus_16S.fasta.log" -o T -n "99_otus_16S.fasta" -i "SILVA123_QIIME_release/rep_set/rep_set_16S_only/99/99_otus_16S.fasta" -p F > "/dev/null" 2> "/dev/null"
StdOut:

StdErr:

Please let me know if you need the configuration file or any other info.

Thank you.

Best regards,
Maria

**Comment by mortonjt** [comment]
Hi @mpachiad .  I'm having trouble finding your question on the qiime forums.  Could you post the link here?

**Comment by mpachiad** [comment]
Good morning,

The message was sent from the lab's email (edgcomb.lab@gmail.com) and the
subject was parallel_assign_taxonomy_blast.py problem.

Here is the link:
https://groups.google.com/forum/#!searchin/qiime-forum/parallel_assign_taxonomy_blast.py$20problem%7Csort:date/qiime-forum/pZiALIROt28/B1yhrrBTEwAJ

Thank you for looking into this. Our IT is aware of the problem and can
help troubleshoot if this is a cluster related issue.

Best regards,
Maria

**Comment by gregcaporaso** [comment]
Closing as this was transferred to the QIIME forum.
