### ISSUE TITLE
rep_set_picking_method not being used

### ISSUE THREAD

**Issue by marijazmf** [biocore/qiime#2175]
I'm running pick_open_reference_otus.py with a parameters file, when I check the log of OTU picking I see:

parameter file values:
```
parallel_pick_otus_uclust_ref:retain_temp_files True
align_seqs:min_length   75
pick_rep_set:rep_set_picking_method     most_abundant
pick_otus:max_rejects   8
pick_otus:max_accepts   1
pick_otus:similarity    0.98
parallel:jobs_to_start  10
```

However, in the pick rep set command I see:
`pick_rep_set.py -i ./step1_otus/seqs_otus.txt -o ./step1_otus/step1_rep_set.fna -f seqs.fna`

Shouldn't it have been run as
`pick_rep_set.py -i ./step1_otus/seqs_otus.txt -o ./step1_otus/step1_rep_set.fna -f seqs.fna -m most_abundant`

?

**Comment by gregcaporaso** [comment]
Can you please post your question to the [QIIME Forum](http://forum.qiime.org)? We try to address these types of technical support questions there, as it's then easier for others to find answers when they have the same questions. Thank you!
