### ISSUE TITLE
installing qiime in Windows System for Linux (WSL)

### ISSUE THREAD

**Issue by pitrack01** [biocore/qiime#2176]
Hello,

I think this is a new issue.  Trying to install qiime on the WSL interface.  Followed the miniconda install procedure then ran test and had two failures.  Any ideas?

(qiime1) pitrack01@LAPTOP-4B9AGN4O:/etc/python2.7$ print_qiime_config.py -t

System information
==================
         Platform:      linux2
   Python version:      2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
Python executable:      /home/pitrack01/anaconda3/envs/qiime1/bin/python

QIIME default reference information
===================================
For details on what files are used as QIIME's default references, see here:
 https://github.com/biocore/qiime-default-reference/releases/tag/0.1.3

Dependency versions
===================
          QIIME library version:        1.9.1
           QIIME script version:        1.9.1
qiime-default-reference version:        0.1.3
                  NumPy version:        1.10.4
                  SciPy version:        0.17.1
                 pandas version:        0.18.1
             matplotlib version:        1.4.3
            biom-format version:        2.1.5
                   h5py version:        Not installed.
                   qcli version:        0.1.1
                   pyqi version:        0.3.2
             scikit-bio version:        0.2.3
                 PyNAST version:        1.2.2
                Emperor version:        0.9.51
                burrito version:        0.9.1
       burrito-fillings version:        0.1.1
              sortmerna version:        SortMeRNA version 2.0, 29/11/2014
              sumaclust version:        SUMACLUST Version 1.0.00
                  swarm version:        Swarm 1.2.19 [Mar  1 2016 23:41:10]
                          gdata:        Installed.

QIIME config values
===================
For definitions of these settings and to learn how to configure QIIME, see here:
 http://qiime.org/install/qiime_config.html
 http://qiime.org/tutorials/parallel_qiime.html

                     blastmat_dir:      None
      pick_otus_reference_seqs_fp:      /home/pitrack01/anaconda3/envs/qiime1/lib/python2.7/site-packages/qiime_default_reference/gg_13_8_otus/rep_set/97_otus.fasta
                         sc_queue:      all.q
      topiaryexplorer_project_dir:      None
     pynast_template_alignment_fp:      /home/pitrack01/anaconda3/envs/qiime1/lib/python2.7/site-packages/qiime_default_reference/gg_13_8_otus/rep_set_aligned/85_otus.pynast.fasta
                  cluster_jobs_fp:      start_parallel_jobs.py
pynast_template_alignment_blastdb:      None
assign_taxonomy_reference_seqs_fp:      /home/pitrack01/anaconda3/envs/qiime1/lib/python2.7/site-packages/qiime_default_reference/gg_13_8_otus/rep_set/97_otus.fasta
                     torque_queue:      friendlyq
                    jobs_to_start:      1
                       slurm_time:      None
            denoiser_min_per_core:      50
assign_taxonomy_id_to_taxonomy_fp:      /home/pitrack01/anaconda3/envs/qiime1/lib/python2.7/site-packages/qiime_default_reference/gg_13_8_otus/taxonomy/97_otu_taxonomy.txt
                         temp_dir:      /tmp/
                     slurm_memory:      None
                      slurm_queue:      None
                      blastall_fp:      blastall
                 seconds_to_sleep:      1

QIIME base install test results
===============================
..F.....F
======================================================================
FAIL: test_cluster_jobs_fp (__main__.QIIMEDependencyBase)
cluster_jobs_fp is set to a valid path and is executable
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pitrack01/anaconda3/envs/qiime1/lib/python2.7/site-packages/qiime-1.9.1-py2.7.egg-info/scripts/print_qiime_config.py", line 224, in test_cluster_jobs_fp
    "cluster_jobs_fp set to an invalid file path or is not in $PATH: %s" % fp)
AssertionError: cluster_jobs_fp set to an invalid file path or is not in $PATH: start_parallel_jobs.py

======================================================================
FAIL: test_uclust_supported_version (__main__.QIIMEDependencyBase)
uclust is in path and version is supported
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pitrack01/anaconda3/envs/qiime1/lib/python2.7/site-packages/qiime-1.9.1-py2.7.egg-info/scripts/print_qiime_config.py", line 336, in test_uclust_supported_version
    % ('.'.join(map(str, acceptable_version)), version_string))
AssertionError: Unsupported uclust version. 1.2.22 is required, but running Segmentation fault (core dumped)
.

----------------------------------------------------------------------
Ran 9 tests in 0.131s

**Comment by gregcaporaso** [comment]
Can you please post your question to the [QIIME Forum](http://forum.qiime.org)? We try to address these types of technical support questions there, as it's then easier for others to find answers when they have the same questions. Thank you!
