### ISSUE TITLE
conda installation issue

### ISSUE THREAD

**Issue by ynakhli** [biocore/qiime#2178]
Hello qiimers,

After I followed the conda installation method from your website: 
http://qiime.org/install/install.html

I can run the print_qiime_config.py nicely and it gives me all dependencies version including Qiime Library and script version 1.9.1
However, qiime can not be found in /bin directory. Thus when typing qiime on command line... it says
"The program 'qiime' is currently not installed. You can install it by typing:
sudo apt-get install qiime"

if i used apt-get... then 1.8 will be installed... I dont want to use that...

I found all the scripts I need, but not qiime in /bin??

Thank you in advance

Regards,

**Comment by mortonjt** [comment]
This sorts of questions would be a better fit on the qiime forums:
https://groups.google.com/forum/#!forum/qiime-forum

Would recommend moving this question over there.

Concerning your problem - what happens if you time `which
print_qiime_config.py`

**Comment by gregcaporaso** [comment]
I'm going to close this issue as it's better suited for the forum as @mortonjt suggested. @ynakhli, if you could answer @mortonjt's question on the forum rather than here that would be helpful. Thanks!
