### ISSUE TITLE
Error in multiple_extract_barcodes.py: Positional argument detected: True

### ISSUE THREAD

**Issue by LaraMacheriotou** [biocore/qiime#2179]
Hi friends of qiime,

I am trying to run the multiple_extract_barcodes.py script in the following way: 

multiple_extract_barcodes.py \
	-i /home/gomre/lmacheriotou/Mocks/data_raw/run2_16_12_16_all \
	-o /home/gomre/lmacheriotou/Mocks/data_raw/extract_barcodes \
	-p /home/gomre/lmacheriotou/Mocks/qiime_files/parameters/extract_barcodes_parameters.txt \
	--paired_data True \
	--read1_indicator _1.fastq \
	--read2_indicator _2.fastq \
	--include_input_dir_path True

I keep getting "Error in multiple_extract_barcodes.py: Positional argument detected: True". It is mentioned in the description that for --paired_data and --include_input_dir_path [default: False], therefore I assume specifying True will change this. Any wisdom on this matter?

**Comment by ElDeveloper** [comment]
@LaraMacheriotou `--include_input_dir_path` is a flag, meaning that its presence implies that the value will be true, if you omit the flag, the value will be false (thus the `default: False`). To correct the "positional argument" error, you have to remove the `True` from the command.

I will close this issue for the time being, but if you have any other questions, please ask them over at the [QIIME forum](http://forum.qiime.org).
