### ISSUE TITLE
computer is 64bit, but qiime virtual box only shows 32bit options

### ISSUE THREAD

**Issue by fpwilson** [biocore/qiime#2181]
I am in the process of installing the qiime virtual box, but when selecting the linus option, it only shows ubuntu 32, not 64. My system is 64bit. how to solve it?

**Comment by ebolyen** [comment]
Hi @fpwilson this should be posted on the [QIIME 1 Forum](https://groups.google.com/forum/#!forum/qiime-forum). I'm going to close this, but it is likely that you have Hyper-V enabled (if you are on Window 10 Pro), you should be able to disable it to see 64-bit images. Please follow up on the forum if needed. Thanks!
