### ISSUE TITLE
Memory issues and OTU picking. 

### ISSUE THREAD

**Issue by Biancabrown** [biocore/qiime#2185]
Hello, 

I'm attempting to run the pick_open_reference_otus.py using uclust61. However, I keep getting the message below. Is there anyways I can get around this? 

Command returned exit status: -9
Stdout:

Stderr
slurmstepd: Exceeded step memory limit at some point.

-Bianca

**Comment by jairideout** [comment]
Can you please post your question on the [QIIME 1 forum](http://forum.qiime.org)? That's where we provide user support.
