### ISSUE TITLE
joining barcodes in dual-index, paired-end sequencing using fastq.join

### ISSUE THREAD

**Issue by Acetylcholine88** [biocore/qiime#2187]
Hi! I am a newbie in bioinformatics/qiime and I am struggling with the analysis of my 16s Illumina run currently. I have 384 samples, 2x300bp, estimated size including primers presumably 637 (Primers are from 27F to 534R), uniquely identified by a combination of 2 barcodes (one in 5-3), (one in 3-5) and I am trying to demulitplex. Pandaseq did not work, I am copying here the error log. I used then fastq.join as an alternative: I would fix the headers of the barcodes first, then join the 2 barcodes first (R3 (forward) - R2 (reverse) and then run the joined_paired_ends commands) and then run split_libraries, incorporating a mapfile for the samples as a mate. It worked but the samples were all definitely wrongly mapped with the mapfile data ( I confirmed that using a known, older database).

Now I am lost and I would be glad about input/ideas. Thank you!

 I wonder if that might be due to an orientation issue of the header

more split_panda_run_jf.e5440699 
Info: panda274assembled_reads_commands.txt contains 40 tasks
Info: average tasks per core: 1.2
getting job id
found job id 5440705
-bash-4.1$ more panda274assembled_reads_wrap.txt.e5440706 
rm: cannot remove `panda274R2_01.fastq.3': No such file or directory
rm: cannot remove `panda274R2_02.fastq.3': No such file or directory
rm: cannot remove `panda274R2_03.fastq.3': No such file or directory
rm: cannot remove `panda274R2_04.fastq.3': No such file or .....

**Comment by jairideout** [comment]
Can you please post your question on the [QIIME 1 forum](http://forum.qiime.org)? That's where we provide user support.
