### ISSUE TITLE
Modernize QIIME for installation and use with Python 3.5

### ISSUE THREAD

**Issue by ajpowel** [biocore/qiime#2188]
Hello,

I would like to install & use QIIME in Python 3.5 environments (both Anaconda & Canopy).  

Would it be possible to modernize QIIME code to this end?

If defined, circumscribed tasks were involved in modernization steps, I could perhaps help.

All the best,

AJP

**Comment by gregcaporaso** [comment]
Hi @ajpowel, This won't change for QIIME 1, but QIIME 2 is Python 3 only. We can discuss further the [QIIME 2 issue that you created](https://github.com/qiime2/qiime2/issues/247). Thanks for your interest in QIIME!
