### ISSUE TITLE
Error when attempting to install qiime on Mac OS X

### ISSUE THREAD

**Issue by foreignsand** [biocore/qiime#2190]
I have no idea what is happening but I get the following error when I try to install qiime:

$ pip install qiime
Collecting qiime
  Using cached qiime-1.9.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/4n/0ghjrzsd4g393zjlgxy9ympc0000gn/T/pip-build-csdegl5r/qiime/setup.py", line 363
        if all([e not in sys.argv for e in 'egg_info', 'sdist', 'register']):
                                                     ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/4n/0ghjrzsd4g393zjlgxy9ympc0000gn/T/pip-build-csdegl5r/qiime/

I've traced the problem [I think] to python setuptools which seem to be installed both for anaconda and python [various versions] but in whatever version is being accessed to install qiime the setup.py command doesn't seem to be working. Or at least this is my interpretation, which could be completely wrong.

Any help would be much appreciated!

**Comment by foreignsand** [comment]
Just a little addendum:

I'm running El Capitan 10.11.6 and am wondering if it's an issue with the OS blocking write privileges to the /usr/bin directory. I opted to install MacQIIME after being unable to install QIIME and discovered this quirk when copying the macqiime command to /usr/bin failed. /usr/local/bin works.

**Comment by jairideout** [comment]
Can you please post your question on the [QIIME 1 forum](http://forum.qiime.org)? That's where we provide user support.
