### ISSUE TITLE
Doesn't install properly on Ubuntu 16 LTS

### ISSUE THREAD

**Issue by xapple** [biocore/qiime#2191]
I just did a `sudo apt-get install qiime` on a Ubuntu 16.04.1 LTS and this is what I get when I run a command:

    xapple@webserver test $ qiime assign_taxonomy
    Traceback (most recent call last):
      File "/usr/lib/qiime/bin/assign_taxonomy.py", line 14, in <module>
        from qiime.util import (parse_command_line_parameters,
      File "/usr/lib/python2.7/dist-packages/qiime/util.py", line 42, in <module>
        from biom.table import DenseTable
    ImportError: cannot import name DenseTable.    

Seems like you still need to work on the installation procedure...

**Comment by antgonza** [comment]
Could you post this kind of questions in the qiime forum: forum.qiime.org?

Note that apt-get is an officially supported qiime install, more info: http://qiime.org/install/install.html

**Comment by xapple** [comment]
Don't have a google account, so no can't post there.

**Comment by antgonza** [comment]
AFAIK you don't need a Google account to join the group + they are free ...

**Comment by xapple** [comment]
Of course you have to be logged in to post in a google group.
It's not a question of account price, but a question of not having a Big Brother account.

Moreover, the thing is not a question, I'm not expecting any answer. Just informing you that users can't use your product, because they can't install it.

**Comment by jairideout** [comment]
I think @antgonza meant to say that `apt-get install qiime` **is not** an officially supported method of installation. We do not maintain nor test the `apt-get` QIIME package, and it is not referenced/recommended in our documentation. We do not provide support for this method of installation.

I recommend contacting the relevant package maintainer if you wish to provide feedback. I believe the BioLinux developers maintain the package.

You can find the officially supported installation methods [here](http://qiime.org/install/index.html).
