### ISSUE TITLE
plot_taxa_summary no html file

### ISSUE THREAD

**Issue by Ros938** [biocore/qiime#2192]
HI there,
first of all thank you for developing those useful and user friendly script! I don't have much experience with this types of analysis but I am quickly learning thanks to you!
Now my question: I am running the plot_taxa_summary.py script including  -c  -s -d and -l options
Unfortunately what I get as output is a .png a pdf. file for each of the chart type selected a .js and a .css file. I am missing the .html file where all the informations are. I am attaching a bar graph and a pie chart as an example of what I get.
Thanks in advance for your time!
[iukxSzDGyHnyQ3NuYpQeiJqoCkCBlL.pdf](https://github.com/biocore/qiime/files/948038/iukxSzDGyHnyQ3NuYpQeiJqoCkCBlL.pdf)
[ktdMlJl1ZCXSCkdbOijfzIQ0pZz8Fi.pdf](https://github.com/biocore/qiime/files/948039/ktdMlJl1ZCXSCkdbOijfzIQ0pZz8Fi.pdf)

**Comment by jairideout** [comment]
Can you please post your question on the [QIIME 1 forum](http://forum.qiime.org)? That's where we provide user support.
