### ISSUE TITLE
Cd-hit with QIIME

### ISSUE THREAD

**Issue by eilenilec** [biocore/qiime#2199]
Hello,

I would like to use cd-hit for the OTU clustering of my data. 
With QIIME, it is possible to use cd-hit with the "pick_otus.py" script but not with the "pick_open_reference_otus.py" one. Is there a reason for that ? Is there a way to perform open-reference clustering with cd-hit within QIIME ? 
Thanks for your help,

Céline

**Comment by jairideout** [comment]
Can you please post your question on the [QIIME 1 forum](http://forum.qiime.org)? That's where we provide user support for QIIME 1.

**Comment by eilenilec** [comment]
I cannot find a way to post a question on the QIIME 1 forum (there is no "new topic" button). :-(
