### ISSUE TITLE
Qiime Install error :  Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-cxxn7r0i/qiime/

### ISSUE THREAD

**Issue by myshu2017-03-14** [biocore/qiime#2201]
Hi,

Recently, I tried to install qiime on ubuntu 16.04.2 LTS following the below commands:

> sudo apt-get install build-essential python-dev python-pip
> pip install numpy
> pip install qiime

But there is a error when I run the `pip install qiime` . 

![image](https://user-images.githubusercontent.com/26398036/29544580-c488cd9a-871b-11e7-87a8-582322004d26.png)

> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kjmfxog8/qiime/

Do you know how to solve it? Looking for your reply. Thank you very much!

Best wishes,
Mingyue Shu

**Comment by jairideout** [comment]
Can you please post your question on the [QIIME 1 forum](http://forum.qiime.org)? That's where we provide user support for QIIME 1.

**Comment by myshu2017-03-14** [comment]
@jairideout Ok, Thank you for your advice.
