### ISSUE TITLE
Losing too many reads after removing primers and joining

### ISSUE THREAD

**Issue by Biancabrown** [biocore/qiime#2202]
Hello, 
 
I was hoping someone on this thread could help. I am currently going through the pipeline and I realize after I use the multiple_extract_barcode.py script to remove my primers(the primers I used to amplify the 16srRNA gene) I have <10% overlap when I join my reads.

For removing barcodes I used the following parameters and  codes:

multiple_extract_barcodes.py -i reads -p 1_barcode_removal_parameter.txt -o 1_nonbarcode_reads --paired_data  --read1_indicator '_R1'  --read2_indicator '_R2' --include_input_dir_path

extract_barcodes:bc1_len 18
extract_barcodes:bc2_len 18
extract_barcodes:input_type barcode_paired_end

After I remove barcodes I proceed to join using the following parameters and  codes:
multiple_join_paired_ends.py -i no_folder_barcode_removed -o joined --read1_indicator 'reads1' --read2_indicator 'reads2' --include_input_dir_path  

join_paired_ends:j 100
join_paired_ends:forward_reads_fp ‘reads1’
join_paired_ends:reverse_reads_fp ‘reads2’
join_paired_ends:perc_max_diff 10

When I checked my sequences I have <10% overlap. If I attempt to overlap without removing primers(multiple_extract_barcodes.py) all my sequences overlap.

I also tried reverse complimenting my R1 reads using Fastx tools. When I do that, nothing overlaps.

Any thoughts?

**Comment by jairideout** [comment]
Can you please post your question on the [QIIME 1 forum](http://forum.qiime.org)? That's where we provide user support for QIIME 1.
