### ISSUE TITLE
What's the difference between collapsed modes "mean vs sum"

### ISSUE THREAD

**Issue by genetalks-fred** [biocore/qiime#2206]
It's may be a stupid question, I'm confused with the difference of collapsed modes, Use sum or mean method collapsed sample's counts in to Groups, the relative abundance of bacterias should be concord or am i misunderstand?
thanks for help!

**Comment by jairideout** [comment]
Can you please post your question on the [QIIME 1 forum](http://forum.qiime.org)? That's where we provide user support for QIIME 1.
