### ISSUE TITLE
Qiime's requirements result in pip trying to install a broken version of emperor

### ISSUE THREAD

**Issue by owainkenwayucl** [biocore/qiime#2212]
I've been re-running some of our old install scripts to test them and I've run across a problem one of my colleagues reported to the emperor developers here: 

https://github.com/biocore/emperor/issues/631

Basically, something has changed in `pip`/`setuptools` which means that emperor 0.9.60 doesn't install successfully from `pip`/pypi.

The emperor devs are working on/have fixed this in 1.x, but unfortunately the requirements for qiime are:

```
emperor<1.0.0,>=0.9.51
```

This presumably means that unless the emperor developers do something odd and backport the fix into a "new old" version of emperor, it's not as trivial to install qiime from `pip` as it used to be.

I've done some testing and it looks like emperor 0.9.51 is fine so it might be enough to restrict the requirements to some version lower than 0.9.60 that works.

**Comment by ElDeveloper** [comment]
Thanks for reporting this @owainkenwayucl! I pushed a patch to fix this problem in the new version of emperor (https://github.com/biocore/emperor/pull/637), however as you note this would have to be backported to fix the problem for QIIME 1.9.x. I'll look into this and see how bad would it be to do that.

**Comment by ElDeveloper** [comment]
I had to update a number of things in our CI build, but all in all it wasn't too bad, this was solved in https://github.com/biocore/emperor/pull/661 . I've pushed out a new maintenance release. Feel free to reopen the issue if you encounter any problems.

**Comment by owainkenwayucl** [comment]
Thanks for this - I'll do a test when I get a chance later today!

**Comment by owainkenwayucl** [comment]
I've done a test and this is indeed working.

Thanks again for your help :)
