### ISSUE TITLE
Basespace Google key issue

### ISSUE THREAD

**Issue by Suchita-Tandon** [biocore/qiime#2226]
I am unable to get 44 letters in my link. After /d & before /pubhtml there are more than 90 letter in my google spreadsheet link. After entering only 44 characters doesn't fix my issue.

What would be the key for the link below :

d/e/2PACX-1vSCGjHbuqL3dREOTlAemeiDdyIB_IdbJYTgyTlyRFq2bdsgrME7-WsnPdh88wkM2uXMUEA8LaxeCkBS/pubhtml?

**Comment by ElDeveloper** [comment]
Did you try clicking on `File > Share > Get Link` in a spreasheet I have that showed me a URL with a 44 character string.

With that being said, the BaseSpace app is _extremely_ out of date and I recommend that you do not use it. I suggest that you use QIIME2 directly. https://qiime2.org
