### ISSUE TITLE
I got problem when running qiime2 env

### ISSUE THREAD

**Issue by VesperLiK** [biocore/qiime#2230]
Every time I activated the qiime2-2020.8, and there would come out the following code, and I don't know how to solve this problem.

(base) vesper@Vesper ~ % conda activate qiime2-2020.8
complete:13: command not found: compdef
/Users/vesper/miniconda3/envs/qiime2-2020.8/bin/tab-qiime:54: /Users/vesper/miniconda3/envs/qiime2-2020.8/bin/qiime: bad interpreter: /Users/vesper/opt/miniconda2/envs/qiime2-2020.8/bin/python: no such file or directory

**Comment by ElDeveloper** [comment]
@VesperLiK can you refer this question to the [QIIME2 forum](https://forum.qiime2.org)? Thanks!
