### ISSUE TITLE
Jensen-Shannon Distance as beta metric

### ISSUE THREAD

**Issue by jansuategui** [biocore/qiime#280]
The Jensen-Shannon Distance (square root of the Jensen-Shannon Divergence) is a true metric distance with good statistical properties and biological interpretation. I was introduced to it by Mani Arumugam of Peer Bork's lab at EMBL...at least a few of the genome sequencing-type bioinformatic people have been using it to look at genome heterogeneity, although it has yet to penetrate into ecology or microbial ecology to any significant extent. It would be great if qiime offered it as a beta diversity metric. Wikipedia link below, Google Scholar will find a number of papers including Lin 1991 and Grosse 2002...or contact me if you want.

http://en.wikipedia.org/wiki/Jensen-Shannon_Divergence

Les Dethlefsen

**Comment by ElDeveloper** [comment]
:+1: to add the ability to call JSD, from some searching around it seems like there's a couple of PRs laying around:

https://github.com/scipy/scipy/pull/3213
https://github.com/scikit-learn/scikit-learn/pull/4191/files

**Comment by domi84** [comment]
Hi Guys,
Any news about this metric?
It's quite useful in Biology. It's a shame that any scientific python module don't support it.
I am trying to use it in combination with k-medoids/PAM clustering (there are some python modules supporting this clustering, but with the classical euclidean distance).

**Comment by gregcaporaso** [comment]
There are no updates (as far as I'm aware) unfortunately. If this were to be added to scikit-bio, it would be accessible through QIIME 2 (note that all development effort is now focused on QIIME 2, not QIIME 1). 

@domi84, would you be interested in opening an issue for this on the scikit-bio issue tracker?

**Comment by domi84** [comment]
@gregcaporaso Thanks, I will.
